// Auto-generated from Tankonomics_Categories_Proposed.xlsx (18 L1 · 224 L2).
// Master company-category tree. Doc id === slug (stable, cross-app join key).
// Seed via Admin → Companies tab → "Seed master tree" (handleSeedCategories).

export interface CategorySeedNode {
  id: string;        // === slug; used as the Firestore document id
  slug: string;
  name: string;
  level: 1 | 2 | 3;
  parentId: string;  // "" for level 1; parent slug for level 2 and 3
  order: number;
}

export const CATEGORY_SEED: CategorySeedNode[] = [
  { id: "storage-terminals", slug: "storage-terminals", name: "Storage Terminals", level: 1, parentId: "", order: 1 },
  { id: "independent-terminals", slug: "independent-terminals", name: "Independent Terminals", level: 2, parentId: "storage-terminals", order: 1 },
  { id: "captive-terminals", slug: "captive-terminals", name: "Captive Terminals", level: 2, parentId: "storage-terminals", order: 2 },
  { id: "process-industries", slug: "process-industries", name: "Process Industries", level: 1, parentId: "", order: 2 },
  { id: "refineries", slug: "refineries", name: "Refineries", level: 2, parentId: "process-industries", order: 1 },
  { id: "petrochemicals", slug: "petrochemicals", name: "Petrochemicals", level: 2, parentId: "process-industries", order: 2 },
  { id: "chemicals", slug: "chemicals", name: "Chemicals", level: 2, parentId: "process-industries", order: 3 },
  { id: "fertilisers", slug: "fertilisers", name: "Fertilisers", level: 2, parentId: "process-industries", order: 4 },
  { id: "industrial-gases", slug: "industrial-gases", name: "Industrial Gases", level: 2, parentId: "process-industries", order: 5 },
  { id: "gas-processing-lng-lpg", slug: "gas-processing-lng-lpg", name: "Gas Processing (LNG/LPG)", level: 2, parentId: "process-industries", order: 6 },
  { id: "biofuels-and-ethanol", slug: "biofuels-and-ethanol", name: "Biofuels & Ethanol", level: 2, parentId: "process-industries", order: 7 },
  { id: "edible-oils-and-fats", slug: "edible-oils-and-fats", name: "Edible Oils & Fats", level: 2, parentId: "process-industries", order: 8 },
  { id: "food-and-beverage-processing", slug: "food-and-beverage-processing", name: "Food & Beverage Processing", level: 2, parentId: "process-industries", order: 9 },
  { id: "pharmaceuticals", slug: "pharmaceuticals", name: "Pharmaceuticals", level: 2, parentId: "process-industries", order: 10 },
  { id: "lubricants-and-bitumen", slug: "lubricants-and-bitumen", name: "Lubricants & Bitumen", level: 2, parentId: "process-industries", order: 11 },
  { id: "natural-resources-and-upstream", slug: "natural-resources-and-upstream", name: "Natural Resources & Upstream", level: 1, parentId: "", order: 3 },
  { id: "oil-and-gas-exploration", slug: "oil-and-gas-exploration", name: "Oil & Gas Exploration", level: 2, parentId: "natural-resources-and-upstream", order: 1 },
  { id: "offshore-production", slug: "offshore-production", name: "Offshore Production", level: 2, parentId: "natural-resources-and-upstream", order: 2 },
  { id: "lng-production", slug: "lng-production", name: "LNG Production", level: 2, parentId: "natural-resources-and-upstream", order: 3 },
  { id: "mining-and-minerals", slug: "mining-and-minerals", name: "Mining & Minerals", level: 2, parentId: "natural-resources-and-upstream", order: 4 },
  { id: "coal", slug: "coal", name: "Coal", level: 2, parentId: "natural-resources-and-upstream", order: 5 },
  { id: "iron-ore", slug: "iron-ore", name: "Iron Ore", level: 2, parentId: "natural-resources-and-upstream", order: 6 },
  { id: "critical-minerals", slug: "critical-minerals", name: "Critical Minerals", level: 2, parentId: "natural-resources-and-upstream", order: 7 },
  { id: "engineering-and-construction", slug: "engineering-and-construction", name: "Engineering & Construction", level: 1, parentId: "", order: 4 },
  { id: "epc-contractors", slug: "epc-contractors", name: "EPC Contractors", level: 2, parentId: "engineering-and-construction", order: 1 },
  { id: "tank-construction", slug: "tank-construction", name: "Tank Construction", level: 2, parentId: "engineering-and-construction", order: 2 },
  { id: "tank-engineering", slug: "tank-engineering", name: "Tank Engineering", level: 2, parentId: "engineering-and-construction", order: 3 },
  { id: "civil-and-structural-engineering", slug: "civil-and-structural-engineering", name: "Civil & Structural Engineering", level: 2, parentId: "engineering-and-construction", order: 4 },
  { id: "foundation-contractors", slug: "foundation-contractors", name: "Foundation Contractors", level: 2, parentId: "engineering-and-construction", order: 5 },
  { id: "piping-contractors", slug: "piping-contractors", name: "Piping Contractors", level: 2, parentId: "engineering-and-construction", order: 6 },
  { id: "mechanical-contractors", slug: "mechanical-contractors", name: "Mechanical Contractors", level: 2, parentId: "engineering-and-construction", order: 7 },
  { id: "electrical-contractors", slug: "electrical-contractors", name: "Electrical Contractors", level: 2, parentId: "engineering-and-construction", order: 8 },
  { id: "instrumentation-contractors", slug: "instrumentation-contractors", name: "Instrumentation Contractors", level: 2, parentId: "engineering-and-construction", order: 9 },
  { id: "insulation-contractors", slug: "insulation-contractors", name: "Insulation Contractors", level: 2, parentId: "engineering-and-construction", order: 10 },
  { id: "painting-and-coating-contractors", slug: "painting-and-coating-contractors", name: "Painting & Coating Contractors", level: 2, parentId: "engineering-and-construction", order: 11 },
  { id: "scaffolding-services", slug: "scaffolding-services", name: "Scaffolding Services", level: 2, parentId: "engineering-and-construction", order: 12 },
  { id: "industrial-flooring", slug: "industrial-flooring", name: "Industrial Flooring", level: 2, parentId: "engineering-and-construction", order: 13 },
  { id: "roofing-systems", slug: "roofing-systems", name: "Roofing Systems", level: 2, parentId: "engineering-and-construction", order: 14 },
  { id: "demolition-and-decommissioning", slug: "demolition-and-decommissioning", name: "Demolition & Decommissioning", level: 2, parentId: "engineering-and-construction", order: 15 },
  { id: "heavy-engineering-and-fabrication", slug: "heavy-engineering-and-fabrication", name: "Heavy Engineering & Fabrication", level: 2, parentId: "engineering-and-construction", order: 16 },
  { id: "tank-maintenance", slug: "tank-maintenance", name: "Tank Maintenance", level: 2, parentId: "engineering-and-construction", order: 17 },
  { id: "surface-preparation-and-blasting", slug: "surface-preparation-and-blasting", name: "Surface Preparation & Blasting", level: 2, parentId: "engineering-and-construction", order: 18 },

  // ── Offshore Floating Systems (L2, added for FPSO/FLNG/FSRU vendor tracking) ─
  // Distinct from "Offshore Production" / "LNG Production" (Natural Resources &
  // Upstream), which are for E&P operators and asset owners. This node is for
  // the contractor side: companies that design, convert, build, lease, and
  // operate floating units as a service (SBM Offshore, MODEC, Yinson, BW
  // Offshore, Bumi Armada) — structurally an EPC/contractor category, not an
  // upstream one.
  { id: "offshore-floating-systems", slug: "offshore-floating-systems", name: "Offshore Floating Systems (FPSO/FSRU/FLNG)", level: 2, parentId: "engineering-and-construction", order: 19 },
  { id: "fpso-fso-design-and-conversion", slug: "fpso-fso-design-and-conversion", name: "FPSO/FSO Design & Conversion", level: 3, parentId: "offshore-floating-systems", order: 1 },
  { id: "flng-systems", slug: "flng-systems", name: "FLNG Systems", level: 3, parentId: "offshore-floating-systems", order: 2 },
  { id: "fsru-and-regasification-systems", slug: "fsru-and-regasification-systems", name: "FSRU & Regasification Systems", level: 3, parentId: "offshore-floating-systems", order: 3 },

  // ── LNG Terminal Engineering (L2, added alongside Offshore Floating Systems) ─
  // EPC and technology-licensing companies for onshore LNG liquefaction/export
  // trains (Air Products, Linde, Chart Industries, Baker Hughes/CLE), separate
  // from Gas Processing (LNG/LPG) under Process Industries, which is for the
  // plant operators, not the engineering contractors.
  { id: "lng-terminal-engineering", slug: "lng-terminal-engineering", name: "LNG Terminal Engineering (Liquefaction & Export)", level: 2, parentId: "engineering-and-construction", order: 20 },

  // ── Process Technology Licensors (L2, added for licensor/technology tracking) ─
  // Companies that license process technology/IP for plant units — distinct
  // from EPC Contractors (who build) and Engineering Consultants under
  // Professional Services (who advise). Serves both Process Industries
  // (refineries, petrochemicals, gas processing) and Natural Resources &
  // Upstream (LNG production) facilities, per the Licensor-Technology Tracker's
  // Category Grouping field.
  { id: "process-technology-licensors", slug: "process-technology-licensors", name: "Process Technology Licensors", level: 2, parentId: "engineering-and-construction", order: 21 },
  { id: "refining-process-technologies", slug: "refining-process-technologies", name: "Refining Process Technologies", level: 3, parentId: "process-technology-licensors", order: 1 },
  { id: "petrochemical-process-technologies", slug: "petrochemical-process-technologies", name: "Petrochemical Process Technologies", level: 3, parentId: "process-technology-licensors", order: 2 },
  { id: "gas-processing-and-lng-technologies", slug: "gas-processing-and-lng-technologies", name: "Gas Processing & LNG Technologies", level: 3, parentId: "process-technology-licensors", order: 3 },
  { id: "fertilizer-process-technologies", slug: "fertilizer-process-technologies", name: "Fertilizer Process Technologies", level: 3, parentId: "process-technology-licensors", order: 4 },

  { id: "tank-systems-and-equipment", slug: "tank-systems-and-equipment", name: "Tank Systems & Equipment", level: 1, parentId: "", order: 5 },
  { id: "tank-gauging", slug: "tank-gauging", name: "Tank Gauging", level: 2, parentId: "tank-systems-and-equipment", order: 1 },
  // ── Level 3 ────────────────────────────────────────────────────────────
  // Tank Gauging is the first L2 to gain sub-types. Custody transfer accuracy
  // is the commercial core of a terminal, and radar / servo / temperature /
  // interface instruments are genuinely different purchases from different
  // vendors — a single flat "Tank Gauging" node hid that.
  //
  // Selecting the L2 remains INCLUSIVE of everything below it, so a company
  // tagged only "radar-level-gauges" still appears under Tank Gauging.
  { id: "radar-level-gauges", slug: "radar-level-gauges", name: "Radar Level Gauges", level: 3, parentId: "tank-gauging", order: 1 },
  { id: "servo-gauges", slug: "servo-gauges", name: "Servo Gauges", level: 3, parentId: "tank-gauging", order: 2 },
  { id: "temperature-measurement-mtt", slug: "temperature-measurement-mtt", name: "Temperature Measurement (MTT)", level: 3, parentId: "tank-gauging", order: 3 },
  { id: "water-interface-detection", slug: "water-interface-detection", name: "Water Interface Detection", level: 3, parentId: "tank-gauging", order: 4 },
  { id: "manual-gauging-equipment", slug: "manual-gauging-equipment", name: "Manual Gauging Equipment", level: 3, parentId: "tank-gauging", order: 5 },
  { id: "tank-sampling-systems", slug: "tank-sampling-systems", name: "Tank Sampling Systems", level: 3, parentId: "tank-gauging", order: 6 },
  { id: "rim-seals", slug: "rim-seals", name: "Rim Seals", level: 2, parentId: "tank-systems-and-equipment", order: 2 },
  { id: "seal-fittings", slug: "seal-fittings", name: "Seal Fittings", level: 2, parentId: "tank-systems-and-equipment", order: 3 },
  { id: "floating-roof-systems", slug: "floating-roof-systems", name: "Floating Roof Systems", level: 2, parentId: "tank-systems-and-equipment", order: 4 },
  { id: "internal-floating-roofs", slug: "internal-floating-roofs", name: "Internal Floating Roofs", level: 2, parentId: "tank-systems-and-equipment", order: 5 },
  { id: "aluminium-dome-roofs", slug: "aluminium-dome-roofs", name: "Aluminium Dome Roofs", level: 2, parentId: "tank-systems-and-equipment", order: 6 },
  { id: "gauge-hatches", slug: "gauge-hatches", name: "Gauge Hatches", level: 2, parentId: "tank-systems-and-equipment", order: 7 },
  { id: "roof-drains", slug: "roof-drains", name: "Roof Drains", level: 2, parentId: "tank-systems-and-equipment", order: 8 },
  { id: "swivel-joint-roof-drains", slug: "swivel-joint-roof-drains", name: "Swivel Joint Roof Drains", level: 3, parentId: "roof-drains", order: 1 },
  { id: "articulated-roof-drains", slug: "articulated-roof-drains", name: "Articulated Roof Drains", level: 3, parentId: "roof-drains", order: 2 },
  { id: "hose-type-roof-drains", slug: "hose-type-roof-drains", name: "Hose-Type Roof Drains", level: 3, parentId: "roof-drains", order: 3 },
  { id: "foam-chambers", slug: "foam-chambers", name: "Foam Chambers", level: 2, parentId: "tank-systems-and-equipment", order: 9 },
  { id: "foam-dams", slug: "foam-dams", name: "Foam Dams", level: 2, parentId: "tank-systems-and-equipment", order: 10 },
  { id: "nozzles-and-manways", slug: "nozzles-and-manways", name: "Nozzles & Manways", level: 2, parentId: "tank-systems-and-equipment", order: 11 },
  { id: "mixers-and-agitators", slug: "mixers-and-agitators", name: "Mixers & Agitators", level: 2, parentId: "tank-systems-and-equipment", order: 12 },
  { id: "heating-systems", slug: "heating-systems", name: "Heating Systems", level: 2, parentId: "tank-systems-and-equipment", order: 13 },
  { id: "tank-blanketing", slug: "tank-blanketing", name: "Tank Blanketing", level: 2, parentId: "tank-systems-and-equipment", order: 14 },
  { id: "vapour-recovery-units-vru", slug: "vapour-recovery-units-vru", name: "Vapour Recovery Units (VRU)", level: 2, parentId: "tank-systems-and-equipment", order: 15 },
  { id: "sludge-recovery-units", slug: "sludge-recovery-units", name: "Sludge Recovery Units", level: 2, parentId: "tank-systems-and-equipment", order: 31 },
  { id: "pressure-vacuum-vents", slug: "pressure-vacuum-vents", name: "Pressure/Vacuum Vents", level: 2, parentId: "tank-systems-and-equipment", order: 16 },
  { id: "emergency-vents", slug: "emergency-vents", name: "Emergency Vents", level: 2, parentId: "tank-systems-and-equipment", order: 17 },
  { id: "flame-arresters", slug: "flame-arresters", name: "Flame Arresters", level: 2, parentId: "tank-systems-and-equipment", order: 18 },
  { id: "breather-valves", slug: "breather-valves", name: "Breather Valves", level: 2, parentId: "tank-systems-and-equipment", order: 19 },
  { id: "conservation-vents", slug: "conservation-vents", name: "Conservation Vents", level: 2, parentId: "tank-systems-and-equipment", order: 20 },
  { id: "floating-suction-systems", slug: "floating-suction-systems", name: "Floating Suction Systems", level: 2, parentId: "tank-systems-and-equipment", order: 21 },
  { id: "water-draw-off-systems", slug: "water-draw-off-systems", name: "Water Draw-Off Systems", level: 2, parentId: "tank-systems-and-equipment", order: 22 },
  { id: "overfill-protection", slug: "overfill-protection", name: "Overfill Protection", level: 2, parentId: "tank-systems-and-equipment", order: 23 },
  { id: "hydraulic-jacking-and-automatic-welding-systems", slug: "hydraulic-jacking-and-automatic-welding-systems", name: "Hydraulic Jacking & Automatic Welding Systems", level: 2, parentId: "tank-systems-and-equipment", order: 24 },
  { id: "bolted-steel-tanks", slug: "bolted-steel-tanks", name: "Bolted Steel Tanks", level: 2, parentId: "tank-systems-and-equipment", order: 25 },
  { id: "industrial-gratings", slug: "industrial-gratings", name: "Industrial Gratings", level: 2, parentId: "tank-systems-and-equipment", order: 26 },
  { id: "industrial-ladders", slug: "industrial-ladders", name: "Industrial Ladders", level: 2, parentId: "tank-systems-and-equipment", order: 27 },
  { id: "industrial-platforms", slug: "industrial-platforms", name: "Industrial Platforms", level: 2, parentId: "tank-systems-and-equipment", order: 28 },
  { id: "cranes-and-lifting-equipment", slug: "cranes-and-lifting-equipment", name: "Cranes & Lifting Equipment", level: 2, parentId: "tank-systems-and-equipment", order: 29 },
  { id: "blasting-and-painting-equipment", slug: "blasting-and-painting-equipment", name: "Blasting & Painting Equipment", level: 2, parentId: "tank-systems-and-equipment", order: 30 },

  // ── Cryogenic & LNG Storage Tanks (L2, added for LNG export terminal session) ─
  // Full-containment / double-wall cryogenic tank manufacturers (9% nickel
  // steel, membrane systems) — a genuinely different vendor set from ambient
  // bolted-steel-tanks above.
  { id: "cryogenic-and-lng-storage-tanks", slug: "cryogenic-and-lng-storage-tanks", name: "Cryogenic & LNG Storage Tanks", level: 2, parentId: "tank-systems-and-equipment", order: 31 },
  { id: "flow-and-transfer-equipment", slug: "flow-and-transfer-equipment", name: "Flow & Transfer Equipment", level: 1, parentId: "", order: 6 },
  { id: "pumps", slug: "pumps", name: "Pumps", level: 2, parentId: "flow-and-transfer-equipment", order: 1 },
  { id: "compressors", slug: "compressors", name: "Compressors", level: 2, parentId: "flow-and-transfer-equipment", order: 2 },
  { id: "blowers", slug: "blowers", name: "Blowers", level: 2, parentId: "flow-and-transfer-equipment", order: 3 },
  { id: "loading-pumps", slug: "loading-pumps", name: "Loading Pumps", level: 2, parentId: "flow-and-transfer-equipment", order: 4 },
  { id: "transfer-pumps", slug: "transfer-pumps", name: "Transfer Pumps", level: 2, parentId: "flow-and-transfer-equipment", order: 5 },
  { id: "metering-pumps", slug: "metering-pumps", name: "Metering Pumps", level: 2, parentId: "flow-and-transfer-equipment", order: 6 },
  { id: "valves", slug: "valves", name: "Valves", level: 2, parentId: "flow-and-transfer-equipment", order: 7 },
  { id: "actuators", slug: "actuators", name: "Actuators", level: 2, parentId: "flow-and-transfer-equipment", order: 8 },
  { id: "flow-meters", slug: "flow-meters", name: "Flow Meters", level: 2, parentId: "flow-and-transfer-equipment", order: 9 },
  { id: "custody-transfer-metering", slug: "custody-transfer-metering", name: "Custody Transfer Metering", level: 2, parentId: "flow-and-transfer-equipment", order: 10 },
  { id: "pigging-systems", slug: "pigging-systems", name: "Pigging Systems", level: 2, parentId: "flow-and-transfer-equipment", order: 11 },
  { id: "strainers", slug: "strainers", name: "Strainers", level: 2, parentId: "flow-and-transfer-equipment", order: 12 },
  { id: "expansion-joints", slug: "expansion-joints", name: "Expansion Joints", level: 2, parentId: "flow-and-transfer-equipment", order: 13 },
  { id: "flexible-hoses", slug: "flexible-hoses", name: "Flexible Hoses", level: 2, parentId: "flow-and-transfer-equipment", order: 14 },
  { id: "loading-arms", slug: "loading-arms", name: "Loading Arms", level: 2, parentId: "flow-and-transfer-equipment", order: 15 },
  { id: "marine-loading-arms", slug: "marine-loading-arms", name: "Marine Loading Arms", level: 2, parentId: "flow-and-transfer-equipment", order: 16 },
  { id: "truck-loading-systems", slug: "truck-loading-systems", name: "Truck Loading Systems", level: 2, parentId: "flow-and-transfer-equipment", order: 17 },
  { id: "rail-loading-systems", slug: "rail-loading-systems", name: "Rail Loading Systems", level: 2, parentId: "flow-and-transfer-equipment", order: 18 },

  // ── Offshore/cryogenic transfer additions (FPSO + LNG export session) ────────
  // Offshore Loading Systems covers single-point mooring (SPM) and CALM buoys —
  // a distinct product line from Marine Loading Arms (fixed jetty arms).
  // Cryogenic Loading Systems covers LNG-specific loading arms/hoses, which use
  // different materials and design standards than ambient marine-loading-arms.
  { id: "offshore-loading-systems-spm-calm", slug: "offshore-loading-systems-spm-calm", name: "Offshore Loading Systems (SPM/CALM)", level: 2, parentId: "flow-and-transfer-equipment", order: 19 },
  { id: "cryogenic-loading-systems-lng", slug: "cryogenic-loading-systems-lng", name: "Cryogenic Loading Systems (LNG)", level: 2, parentId: "flow-and-transfer-equipment", order: 20 },
  { id: "heat-exchangers", slug: "heat-exchangers", name: "Heat Exchangers", level: 2, parentId: "flow-and-transfer-equipment", order: 21 },
  { id: "filtration-and-separation-technology", slug: "filtration-and-separation-technology", name: "Filtration & Separation Technology", level: 2, parentId: "flow-and-transfer-equipment", order: 22 },
  { id: "membrane-technologies", slug: "membrane-technologies", name: "Membrane Technologies", level: 2, parentId: "flow-and-transfer-equipment", order: 23 },
  { id: "rotating-equipment-and-gearboxes", slug: "rotating-equipment-and-gearboxes", name: "Rotating Equipment & Gearboxes", level: 2, parentId: "flow-and-transfer-equipment", order: 24 },
  { id: "instrumentation-and-automation", slug: "instrumentation-and-automation", name: "Instrumentation & Automation", level: 1, parentId: "", order: 7 },
  { id: "terminal-automation", slug: "terminal-automation", name: "Terminal Automation", level: 2, parentId: "instrumentation-and-automation", order: 1 },
  { id: "scada-systems", slug: "scada-systems", name: "SCADA Systems", level: 2, parentId: "instrumentation-and-automation", order: 2 },
  { id: "plc-and-dcs", slug: "plc-and-dcs", name: "PLC & DCS", level: 2, parentId: "instrumentation-and-automation", order: 3 },
  { id: "tank-inventory-systems", slug: "tank-inventory-systems", name: "Tank Inventory Systems", level: 2, parentId: "instrumentation-and-automation", order: 4 },
  { id: "remote-monitoring", slug: "remote-monitoring", name: "Remote Monitoring", level: 2, parentId: "instrumentation-and-automation", order: 5 },
  { id: "industrial-networking", slug: "industrial-networking", name: "Industrial Networking", level: 2, parentId: "instrumentation-and-automation", order: 6 },
  { id: "electrical-and-instrumentation", slug: "electrical-and-instrumentation", name: "Electrical & Instrumentation", level: 2, parentId: "instrumentation-and-automation", order: 7 },
  { id: "site-communication-systems", slug: "site-communication-systems", name: "Site Communication Systems", level: 2, parentId: "instrumentation-and-automation", order: 8 },
  { id: "digital-ai-and-robotics", slug: "digital-ai-and-robotics", name: "Digital, AI & Robotics", level: 1, parentId: "", order: 8 },
  { id: "industrial-software", slug: "industrial-software", name: "Industrial Software", level: 2, parentId: "digital-ai-and-robotics", order: 1 },
  { id: "erp-solutions", slug: "erp-solutions", name: "ERP Solutions", level: 2, parentId: "digital-ai-and-robotics", order: 2 },
  { id: "cmms-eam", slug: "cmms-eam", name: "CMMS / EAM", level: 2, parentId: "digital-ai-and-robotics", order: 3 },
  { id: "gis-platforms", slug: "gis-platforms", name: "GIS Platforms", level: 2, parentId: "digital-ai-and-robotics", order: 4 },
  { id: "cloud-services", slug: "cloud-services", name: "Cloud Services", level: 2, parentId: "digital-ai-and-robotics", order: 5 },
  { id: "ai-and-analytics", slug: "ai-and-analytics", name: "AI & Analytics", level: 2, parentId: "digital-ai-and-robotics", order: 6 },
  { id: "data-integration", slug: "data-integration", name: "Data Integration", level: 2, parentId: "digital-ai-and-robotics", order: 7 },
  { id: "digital-twins", slug: "digital-twins", name: "Digital Twins", level: 2, parentId: "digital-ai-and-robotics", order: 8 },
  { id: "industrial-iot", slug: "industrial-iot", name: "Industrial IoT", level: 2, parentId: "digital-ai-and-robotics", order: 9 },
  { id: "predictive-maintenance", slug: "predictive-maintenance", name: "Predictive Maintenance", level: 2, parentId: "digital-ai-and-robotics", order: 10 },
  { id: "asset-performance-management", slug: "asset-performance-management", name: "Asset Performance Management", level: 2, parentId: "digital-ai-and-robotics", order: 11 },
  { id: "bim-services", slug: "bim-services", name: "BIM Services", level: 2, parentId: "digital-ai-and-robotics", order: 12 },
  { id: "digital-documentation", slug: "digital-documentation", name: "Digital Documentation", level: 2, parentId: "digital-ai-and-robotics", order: 13 },
  { id: "saas-providers", slug: "saas-providers", name: "SaaS Providers", level: 2, parentId: "digital-ai-and-robotics", order: 14 },
  { id: "cybersecurity", slug: "cybersecurity", name: "Cybersecurity", level: 2, parentId: "digital-ai-and-robotics", order: 15 },
  { id: "drone-and-robotic-inspection", slug: "drone-and-robotic-inspection", name: "Drone & Robotic Inspection", level: 2, parentId: "digital-ai-and-robotics", order: 16 },
  { id: "autonomous-inspection-robots", slug: "autonomous-inspection-robots", name: "Autonomous Inspection Robots", level: 2, parentId: "digital-ai-and-robotics", order: 17 },
  { id: "cctv-and-video-analytics", slug: "cctv-and-video-analytics", name: "CCTV & Video Analytics", level: 2, parentId: "digital-ai-and-robotics", order: 18 },
  { id: "laser-scanning-and-lidar", slug: "laser-scanning-and-lidar", name: "Laser Scanning & LiDAR", level: 2, parentId: "digital-ai-and-robotics", order: 19 },
  { id: "asset-integrity-and-inspection", slug: "asset-integrity-and-inspection", name: "Asset Integrity & Inspection", level: 1, parentId: "", order: 9 },
  { id: "tank-inspection", slug: "tank-inspection", name: "Tank Inspection", level: 2, parentId: "asset-integrity-and-inspection", order: 1 },
  { id: "non-destructive-testing-ndt", slug: "non-destructive-testing-ndt", name: "Non-Destructive Testing (NDT)", level: 2, parentId: "asset-integrity-and-inspection", order: 2 },
  { id: "corrosion-monitoring", slug: "corrosion-monitoring", name: "Corrosion Monitoring", level: 2, parentId: "asset-integrity-and-inspection", order: 3 },
  { id: "corrosion-protection", slug: "corrosion-protection", name: "Corrosion Protection", level: 2, parentId: "asset-integrity-and-inspection", order: 4 },
  { id: "cathodic-protection", slug: "cathodic-protection", name: "Cathodic Protection", level: 2, parentId: "asset-integrity-and-inspection", order: 5 },
  { id: "protective-coatings", slug: "protective-coatings", name: "Protective Coatings", level: 2, parentId: "asset-integrity-and-inspection", order: 6 },
  { id: "coatings-and-linings", slug: "coatings-and-linings", name: "Coatings & Linings", level: 2, parentId: "asset-integrity-and-inspection", order: 7 },
  { id: "refractory-services", slug: "refractory-services", name: "Refractory Services", level: 2, parentId: "asset-integrity-and-inspection", order: 8 },
  { id: "integrity-management", slug: "integrity-management", name: "Integrity Management", level: 2, parentId: "asset-integrity-and-inspection", order: 9 },
  { id: "risk-based-inspection-rbi", slug: "risk-based-inspection-rbi", name: "Risk-Based Inspection (RBI)", level: 2, parentId: "asset-integrity-and-inspection", order: 10 },
  { id: "fitness-for-service", slug: "fitness-for-service", name: "Fitness-for-Service", level: 2, parentId: "asset-integrity-and-inspection", order: 11 },
  { id: "life-extension", slug: "life-extension", name: "Life Extension", level: 2, parentId: "asset-integrity-and-inspection", order: 12 },
  { id: "tank-cleaning", slug: "tank-cleaning", name: "Tank Cleaning", level: 2, parentId: "asset-integrity-and-inspection", order: 13 },
  { id: "robotic-no-man-entry-cleaning", slug: "robotic-no-man-entry-cleaning", name: "Robotic & No-Man-Entry Cleaning", level: 3, parentId: "tank-cleaning", order: 1 },
  { id: "manual-confined-space-cleaning", slug: "manual-confined-space-cleaning", name: "Manual & Confined-Space Cleaning", level: 3, parentId: "tank-cleaning", order: 2 },
  { id: "degassing-and-vapour-freeing", slug: "degassing-and-vapour-freeing", name: "Degassing & Vapour Freeing", level: 3, parentId: "tank-cleaning", order: 3 },
  { id: "hydrotesting", slug: "hydrotesting", name: "Hydrotesting", level: 2, parentId: "asset-integrity-and-inspection", order: 14 },
  { id: "calibration-services", slug: "calibration-services", name: "Calibration Services", level: 2, parentId: "asset-integrity-and-inspection", order: 15 },
  { id: "rope-access-services", slug: "rope-access-services", name: "Rope Access Services", level: 2, parentId: "asset-integrity-and-inspection", order: 16 },
  { id: "leak-detection", slug: "leak-detection", name: "Leak Detection", level: 2, parentId: "asset-integrity-and-inspection", order: 17 },
  { id: "sludge-removal", slug: "sludge-removal", name: "Sludge Removal", level: 2, parentId: "asset-integrity-and-inspection", order: 18 },
  { id: "hydrocarbon-recovery", slug: "hydrocarbon-recovery", name: "Hydrocarbon Recovery", level: 3, parentId: "sludge-removal", order: 1 },
  { id: "catalyst-handling", slug: "catalyst-handling", name: "Catalyst Handling", level: 2, parentId: "asset-integrity-and-inspection", order: 19 },
  { id: "fire-safety-and-environment", slug: "fire-safety-and-environment", name: "Fire, Safety & Environment", level: 1, parentId: "", order: 10 },
  { id: "fire-protection", slug: "fire-protection", name: "Fire Protection", level: 2, parentId: "fire-safety-and-environment", order: 1 },
  { id: "foam-systems-and-equipment", slug: "foam-systems-and-equipment", name: "Foam Systems & Equipment", level: 3, parentId: "fire-protection", order: 1 },
  { id: "fire-water-systems", slug: "fire-water-systems", name: "Fire Water Systems", level: 3, parentId: "fire-protection", order: 2 },
  { id: "portable-fire-equipment", slug: "portable-fire-equipment", name: "Portable Fire Equipment", level: 3, parentId: "fire-protection", order: 3 },
  { id: "fire-detection", slug: "fire-detection", name: "Fire Detection", level: 2, parentId: "fire-safety-and-environment", order: 2 },
  { id: "fire-fighting-foam", slug: "fire-fighting-foam", name: "Fire Fighting Foam", level: 2, parentId: "fire-safety-and-environment", order: 3 },
  { id: "rim-seal-fire-protection", slug: "rim-seal-fire-protection", name: "Rim Seal Fire Protection", level: 2, parentId: "fire-safety-and-environment", order: 4 },
  { id: "rim-seal-foam-pourers", slug: "rim-seal-foam-pourers", name: "Rim Seal Foam Pourers", level: 3, parentId: "rim-seal-fire-protection", order: 1 },
  { id: "rim-seal-detection-systems", slug: "rim-seal-detection-systems", name: "Rim Seal Detection Systems", level: 3, parentId: "rim-seal-fire-protection", order: 2 },
  { id: "rim-seal-dry-chemical-systems", slug: "rim-seal-dry-chemical-systems", name: "Rim Seal Dry Chemical Systems", level: 3, parentId: "rim-seal-fire-protection", order: 3 },
  { id: "gas-detection", slug: "gas-detection", name: "Gas Detection", level: 2, parentId: "fire-safety-and-environment", order: 5 },
  { id: "emergency-shutdown-systems", slug: "emergency-shutdown-systems", name: "Emergency Shutdown Systems", level: 2, parentId: "fire-safety-and-environment", order: 6 },
  { id: "explosion-protection-atex", slug: "explosion-protection-atex", name: "Explosion Protection (ATEX)", level: 2, parentId: "fire-safety-and-environment", order: 7 },
  { id: "hazardous-area-equipment", slug: "hazardous-area-equipment", name: "Hazardous Area Equipment", level: 2, parentId: "fire-safety-and-environment", order: 8 },
  { id: "hazardous-area-lighting", slug: "hazardous-area-lighting", name: "Hazardous Area Lighting", level: 3, parentId: "hazardous-area-equipment", order: 1 },
  { id: "lightning-protection", slug: "lightning-protection", name: "Lightning Protection", level: 2, parentId: "fire-safety-and-environment", order: 9 },
  { id: "bypass-conductors", slug: "bypass-conductors", name: "Bypass Conductors", level: 3, parentId: "lightning-protection", order: 1 },
  { id: "submerged-shunts", slug: "submerged-shunts", name: "Submerged Shunts", level: 3, parentId: "lightning-protection", order: 2 },
  { id: "surge-protection-devices", slug: "surge-protection-devices", name: "Surge Protection Devices", level: 3, parentId: "lightning-protection", order: 3 },
  { id: "air-terminals-and-strike-termination-devices", slug: "air-terminals-and-strike-termination-devices", name: "Air Terminals & Strike Termination Devices", level: 3, parentId: "lightning-protection", order: 4 },
  { id: "charge-dissipation-systems", slug: "charge-dissipation-systems", name: "Charge Dissipation Systems", level: 3, parentId: "lightning-protection", order: 5 },
  { id: "in-tank-potential-equalizers", slug: "in-tank-potential-equalizers", name: "In-Tank Potential Equalizers", level: 3, parentId: "lightning-protection", order: 6 },
  { id: "earthing-and-bonding", slug: "earthing-and-bonding", name: "Earthing & Bonding", level: 2, parentId: "fire-safety-and-environment", order: 10 },
  { id: "spill-containment", slug: "spill-containment", name: "Spill Containment", level: 2, parentId: "fire-safety-and-environment", order: 11 },
  { id: "containment-liners-and-geomembranes", slug: "containment-liners-and-geomembranes", name: "Containment Liners & Geomembranes", level: 3, parentId: "spill-containment", order: 1 },
  { id: "spill-response-equipment", slug: "spill-response-equipment", name: "Spill Response Equipment", level: 3, parentId: "spill-containment", order: 2 },
  { id: "environmental-monitoring", slug: "environmental-monitoring", name: "Environmental Monitoring", level: 2, parentId: "fire-safety-and-environment", order: 12 },
  { id: "occupational-safety", slug: "occupational-safety", name: "Occupational Safety", level: 2, parentId: "fire-safety-and-environment", order: 13 },
  { id: "hazop-and-risk-assessment", slug: "hazop-and-risk-assessment", name: "HAZOP & Risk Assessment", level: 2, parentId: "fire-safety-and-environment", order: 14 },
  { id: "functional-safety", slug: "functional-safety", name: "Functional Safety", level: 2, parentId: "fire-safety-and-environment", order: 15 },
  { id: "process-safety", slug: "process-safety", name: "Process Safety", level: 2, parentId: "fire-safety-and-environment", order: 16 },
  { id: "regulatory-compliance", slug: "regulatory-compliance", name: "Regulatory Compliance", level: 2, parentId: "fire-safety-and-environment", order: 17 },
  
  { id: "materials-and-metallurgy", slug: "materials-and-metallurgy", name: "Materials & Metallurgy", level: 1, parentId: "", order: 11 },
  { id: "steel-manufacturers", slug: "steel-manufacturers", name: "Steel Manufacturers", level: 2, parentId: "materials-and-metallurgy", order: 1 },
  { id: "stainless-steel", slug: "stainless-steel", name: "Stainless Steel", level: 2, parentId: "materials-and-metallurgy", order: 2 },
  { id: "alloy-steel", slug: "alloy-steel", name: "Alloy Steel", level: 2, parentId: "materials-and-metallurgy", order: 3 },
  { id: "aluminium-products", slug: "aluminium-products", name: "Aluminium Products", level: 2, parentId: "materials-and-metallurgy", order: 4 },
  { id: "pipes-and-tubes", slug: "pipes-and-tubes", name: "Pipes & Tubes", level: 2, parentId: "materials-and-metallurgy", order: 5 },
  { id: "plates-and-sheets", slug: "plates-and-sheets", name: "Plates & Sheets", level: 2, parentId: "materials-and-metallurgy", order: 6 },
  { id: "structural-steel", slug: "structural-steel", name: "Structural Steel", level: 2, parentId: "materials-and-metallurgy", order: 7 },
  { id: "forgings", slug: "forgings", name: "Forgings", level: 2, parentId: "materials-and-metallurgy", order: 8 },
  { id: "castings", slug: "castings", name: "Castings", level: 2, parentId: "materials-and-metallurgy", order: 9 },
  { id: "composite-materials", slug: "composite-materials", name: "Composite Materials", level: 2, parentId: "materials-and-metallurgy", order: 10 },
  { id: "frp-products", slug: "frp-products", name: "FRP Products", level: 2, parentId: "materials-and-metallurgy", order: 11 },
  { id: "hdpe-products", slug: "hdpe-products", name: "HDPE Products", level: 2, parentId: "materials-and-metallurgy", order: 12 },
  { id: "cable-manufacturers", slug: "cable-manufacturers", name: "Cable Manufacturers", level: 2, parentId: "materials-and-metallurgy", order: 13 },
  // Civil/construction materials. The sheet above is metals- and polymer-led;
  // these cover what actually goes into tank foundations, ring beams and bund
  // walls. Refractory and insulation MATERIALS are added here deliberately as
  // the counterparts to AX-08 Refractory Services and EC-10 Insulation
  // Contractors, which previously had no materials-side equivalent.
  { id: "ready-mix-concrete", slug: "ready-mix-concrete", name: "Ready Mix Concrete", level: 2, parentId: "materials-and-metallurgy", order: 14 },
  { id: "cement-and-aggregates", slug: "cement-and-aggregates", name: "Cement & Aggregates", level: 2, parentId: "materials-and-metallurgy", order: 15 },
  { id: "refractory-materials", slug: "refractory-materials", name: "Refractory Materials", level: 2, parentId: "materials-and-metallurgy", order: 16 },
  { id: "insulation-materials", slug: "insulation-materials", name: "Insulation Materials", level: 2, parentId: "materials-and-metallurgy", order: 17 },
  // Added to match TWI's MM-18 — secondary/recycled metals (lead, aluminium,
  // copper) reclaimed from batteries and scrap, distinct from the primary
  // steel/aluminium producers above.
  { id: "secondary-metals-and-recycling", slug: "secondary-metals-and-recycling", name: "Secondary Metals & Recycling", level: 2, parentId: "materials-and-metallurgy", order: 18 },
  { id: "catalysts-and-adsorbents", slug: "catalysts-and-adsorbents", name: "Catalysts & Adsorbents", level: 2, parentId: "materials-and-metallurgy", order: 19 },
  { id: "electrical-equipment-and-transformers", slug: "electrical-equipment-and-transformers", name: "Electrical Equipment & Transformers", level: 2, parentId: "materials-and-metallurgy", order: 20 },
  { id: "industrial-supplies-mro", slug: "industrial-supplies-mro", name: "Industrial Supplies (MRO)", level: 1, parentId: "", order: 12 },
  { id: "fasteners", slug: "fasteners", name: "Fasteners", level: 2, parentId: "industrial-supplies-mro", order: 1 },
  { id: "gaskets", slug: "gaskets", name: "Gaskets", level: 2, parentId: "industrial-supplies-mro", order: 2 },
  { id: "welding-equipment-and-consumables", slug: "welding-equipment-and-consumables", name: "Welding Equipment & Consumables", level: 2, parentId: "industrial-supplies-mro", order: 3 },
  { id: "fasteners-and-bolting", slug: "fasteners-and-bolting", name: "Fasteners & Bolting", level: 2, parentId: "industrial-supplies-mro", order: 4 },
  { id: "bearings", slug: "bearings", name: "Bearings", level: 2, parentId: "industrial-supplies-mro", order: 3 },
  { id: "industrial-lubricants", slug: "industrial-lubricants", name: "Industrial Lubricants", level: 2, parentId: "industrial-supplies-mro", order: 4 },
  { id: "industrial-hoses", slug: "industrial-hoses", name: "Industrial Hoses", level: 2, parentId: "industrial-supplies-mro", order: 5 },
  { id: "industrial-rubber", slug: "industrial-rubber", name: "Industrial Rubber", level: 2, parentId: "industrial-supplies-mro", order: 6 },
  { id: "sealing-products", slug: "sealing-products", name: "Sealing Products", level: 2, parentId: "industrial-supplies-mro", order: 7 },
  { id: "industrial-plastics", slug: "industrial-plastics", name: "Industrial Plastics", level: 2, parentId: "industrial-supplies-mro", order: 8 },
  { id: "industrial-chemicals", slug: "industrial-chemicals", name: "Industrial Chemicals", level: 2, parentId: "industrial-supplies-mro", order: 9 },
  { id: "welding-consumables", slug: "welding-consumables", name: "Welding Consumables", level: 2, parentId: "industrial-supplies-mro", order: 10 },
  { id: "abrasives", slug: "abrasives", name: "Abrasives", level: 2, parentId: "industrial-supplies-mro", order: 11 },
  { id: "industrial-adhesives", slug: "industrial-adhesives", name: "Industrial Adhesives", level: 2, parentId: "industrial-supplies-mro", order: 12 },
  { id: "industrial-safety-equipment", slug: "industrial-safety-equipment", name: "Industrial Safety Equipment", level: 2, parentId: "industrial-supplies-mro", order: 13 },
  { id: "hand-tools", slug: "hand-tools", name: "Hand Tools", level: 2, parentId: "industrial-supplies-mro", order: 14 },
  { id: "power-tools", slug: "power-tools", name: "Power Tools", level: 2, parentId: "industrial-supplies-mro", order: 15 },
  { id: "logistics-and-transportation", slug: "logistics-and-transportation", name: "Logistics & Transportation", level: 1, parentId: "", order: 13 },
  { id: "port-operators", slug: "port-operators", name: "Port Operators", level: 2, parentId: "logistics-and-transportation", order: 1 },
  { id: "pipeline-operators", slug: "pipeline-operators", name: "Pipeline Operators", level: 2, parentId: "logistics-and-transportation", order: 2 },
  { id: "marine-logistics", slug: "marine-logistics", name: "Marine Logistics", level: 2, parentId: "logistics-and-transportation", order: 3 },
  { id: "shipping-companies", slug: "shipping-companies", name: "Shipping Companies", level: 2, parentId: "logistics-and-transportation", order: 4 },
  { id: "inland-waterways", slug: "inland-waterways", name: "Inland Waterways", level: 2, parentId: "logistics-and-transportation", order: 5 },
  { id: "rail-logistics", slug: "rail-logistics", name: "Rail Logistics", level: 2, parentId: "logistics-and-transportation", order: 6 },
  { id: "trucking-and-road-tankers", slug: "trucking-and-road-tankers", name: "Trucking & Road Tankers", level: 2, parentId: "logistics-and-transportation", order: 7 },
  { id: "freight-forwarding", slug: "freight-forwarding", name: "Freight Forwarding", level: 2, parentId: "logistics-and-transportation", order: 8 },
  { id: "customs-and-port-services", slug: "customs-and-port-services", name: "Customs & Port Services", level: 2, parentId: "logistics-and-transportation", order: 9 },
  { id: "warehouse-operators", slug: "warehouse-operators", name: "Warehouse Operators", level: 2, parentId: "logistics-and-transportation", order: 10 },
  { id: "cold-storage", slug: "cold-storage", name: "Cold Storage", level: 2, parentId: "logistics-and-transportation", order: 11 },
  { id: "heavy-lift-and-transport", slug: "heavy-lift-and-transport", name: "Heavy Lift & Transport", level: 2, parentId: "logistics-and-transportation", order: 12 },
  { id: "marine-and-port-equipment", slug: "marine-and-port-equipment", name: "Marine & Port Equipment", level: 2, parentId: "logistics-and-transportation", order: 12 },
  { id: "utilities-and-energy", slug: "utilities-and-energy", name: "Utilities & Energy", level: 1, parentId: "", order: 14 },
  { id: "industrial-water-systems", slug: "industrial-water-systems", name: "Industrial Water Systems", level: 2, parentId: "utilities-and-energy", order: 1 },
  { id: "wastewater-treatment", slug: "wastewater-treatment", name: "Wastewater Treatment", level: 2, parentId: "utilities-and-energy", order: 2 },
  { id: "desalination", slug: "desalination", name: "Desalination", level: 2, parentId: "utilities-and-energy", order: 3 },
  { id: "steam-systems", slug: "steam-systems", name: "Steam Systems", level: 2, parentId: "utilities-and-energy", order: 4 },
  { id: "compressed-air", slug: "compressed-air", name: "Compressed Air", level: 2, parentId: "utilities-and-energy", order: 5 },
  { id: "power-generation", slug: "power-generation", name: "Power Generation", level: 2, parentId: "utilities-and-energy", order: 6 },
  // Emergency and standby power is a regulatory requirement at terminals, not
  // an optional extra — it runs fire water pumps, ESD and emergency lighting
  // when mains fails. These are genuinely different products from different
  // vendors, so they sit as L3 under Power Generation.
  { id: "diesel-generators", slug: "diesel-generators", name: "Diesel Generators & Gensets", level: 3, parentId: "power-generation", order: 1 },
  { id: "ups-systems", slug: "ups-systems", name: "UPS Systems", level: 3, parentId: "power-generation", order: 2 },
  { id: "power-distribution-equipment", slug: "power-distribution-equipment", name: "Power Distribution Equipment", level: 3, parentId: "power-generation", order: 3 },
  { id: "hydrogen-infrastructure", slug: "hydrogen-infrastructure", name: "Hydrogen Infrastructure", level: 2, parentId: "utilities-and-energy", order: 9 },
  { id: "utility-contractors", slug: "utility-contractors", name: "Utility Contractors", level: 2, parentId: "utilities-and-energy", order: 10 },
  { id: "industrial-burners-and-boilers", slug: "industrial-burners-and-boilers", name: "Industrial Burners & Boilers", level: 2, parentId: "utilities-and-energy", order: 11 },
  { id: "sustainability-and-energy-transition", slug: "sustainability-and-energy-transition", name: "Sustainability & Energy Transition", level: 1, parentId: "", order: 15 },
  { id: "carbon-capture", slug: "carbon-capture", name: "Carbon Capture", level: 2, parentId: "sustainability-and-energy-transition", order: 1 },
  { id: "methane-reduction", slug: "methane-reduction", name: "Methane Reduction", level: 2, parentId: "sustainability-and-energy-transition", order: 2 },
  { id: "emissions-management", slug: "emissions-management", name: "Emissions Management", level: 2, parentId: "sustainability-and-energy-transition", order: 3 },
  { id: "emissions-control", slug: "emissions-control", name: "Emissions Control", level: 2, parentId: "sustainability-and-energy-transition", order: 4 },
  { id: "esg-consulting", slug: "esg-consulting", name: "ESG Consulting", level: 2, parentId: "sustainability-and-energy-transition", order: 5 },
  { id: "carbon-accounting", slug: "carbon-accounting", name: "Carbon Accounting", level: 2, parentId: "sustainability-and-energy-transition", order: 6 },
  { id: "renewable-fuels", slug: "renewable-fuels", name: "Renewable Fuels", level: 2, parentId: "sustainability-and-energy-transition", order: 7 },
  { id: "sustainable-aviation-fuel", slug: "sustainable-aviation-fuel", name: "Sustainable Aviation Fuel", level: 2, parentId: "sustainability-and-energy-transition", order: 8 },
  { id: "hydrogen-and-ammonia", slug: "hydrogen-and-ammonia", name: "Hydrogen & Ammonia", level: 2, parentId: "sustainability-and-energy-transition", order: 9 },
  { id: "circular-economy", slug: "circular-economy", name: "Circular Economy", level: 2, parentId: "sustainability-and-energy-transition", order: 10 },
  { id: "waste-management", slug: "waste-management", name: "Waste Management", level: 2, parentId: "sustainability-and-energy-transition", order: 11 },
  { id: "water-reuse", slug: "water-reuse", name: "Water Reuse", level: 2, parentId: "sustainability-and-energy-transition", order: 12 },
  { id: "net-zero-solutions", slug: "net-zero-solutions", name: "Net Zero Solutions", level: 2, parentId: "sustainability-and-energy-transition", order: 13 },
  { id: "professional-services", slug: "professional-services", name: "Professional Services", level: 1, parentId: "", order: 16 },
  { id: "project-consultants", slug: "project-consultants", name: "Project Consultants", level: 2, parentId: "professional-services", order: 1 },
  { id: "engineering-consultants", slug: "engineering-consultants", name: "Engineering Consultants", level: 2, parentId: "professional-services", order: 2 },
  { id: "consultancy-services", slug: "consultancy-services", name: "Consultancy Services", level: 2, parentId: "professional-services", order: 3 },
  { id: "owner-s-engineers", slug: "owner-s-engineers", name: "Owner's Engineers", level: 2, parentId: "professional-services", order: 4 },
  { id: "pmc-services", slug: "pmc-services", name: "PMC Services", level: 2, parentId: "professional-services", order: 5 },
  { id: "surveying", slug: "surveying", name: "Surveying", level: 2, parentId: "professional-services", order: 6 },
  { id: "gis-services", slug: "gis-services", name: "GIS Services", level: 2, parentId: "professional-services", order: 7 },
  { id: "environmental-consultants", slug: "environmental-consultants", name: "Environmental Consultants", level: 2, parentId: "professional-services", order: 8 },
  { id: "legal-services", slug: "legal-services", name: "Legal Services", level: 2, parentId: "professional-services", order: 9 },
  { id: "insurance", slug: "insurance", name: "Insurance", level: 2, parentId: "professional-services", order: 10 },
  { id: "financial-advisory", slug: "financial-advisory", name: "Financial Advisory", level: 2, parentId: "professional-services", order: 11 },
  { id: "digital-transformation", slug: "digital-transformation", name: "Digital Transformation", level: 2, parentId: "professional-services", order: 12 },
  { id: "procurement-services", slug: "procurement-services", name: "Procurement Services", level: 2, parentId: "professional-services", order: 13 },
  // Moved from Fire, Safety & Environment: this is a SERVICE function, not a
  // fire/safety product. Its occupants (Bureau Veritas, TUV SUD, SGS) sit
  // naturally here. The SLUG IS UNCHANGED, so no company needs re-tagging —
  // only the parent moves.
  { id: "inspection-and-certification", slug: "inspection-and-certification", name: "Inspection & Certification", level: 2, parentId: "professional-services", order: 14 },
  { id: "training-and-workforce", slug: "training-and-workforce", name: "Training & Workforce", level: 1, parentId: "", order: 17 },
  { id: "recruitment-and-jobs", slug: "recruitment-and-jobs", name: "Recruitment & Jobs", level: 2, parentId: "training-and-workforce", order: 1 },
  { id: "training-and-skilling", slug: "training-and-skilling", name: "Training & Skilling", level: 2, parentId: "training-and-workforce", order: 2 },
  { id: "technical-institutes", slug: "technical-institutes", name: "Technical Institutes", level: 2, parentId: "training-and-workforce", order: 3 },
  { id: "certification-bodies", slug: "certification-bodies", name: "Certification Bodies", level: 2, parentId: "training-and-workforce", order: 4 },
  { id: "industrial-staffing", slug: "industrial-staffing", name: "Industrial Staffing", level: 2, parentId: "training-and-workforce", order: 5 },
  { id: "contract-labour", slug: "contract-labour", name: "Contract Labour", level: 2, parentId: "training-and-workforce", order: 6 },
  { id: "executive-search", slug: "executive-search", name: "Executive Search", level: 2, parentId: "training-and-workforce", order: 7 },
  { id: "online-learning", slug: "online-learning", name: "Online Learning", level: 2, parentId: "training-and-workforce", order: 8 },
  { id: "competency-assessment", slug: "competency-assessment", name: "Competency Assessment", level: 2, parentId: "training-and-workforce", order: 9 },
  { id: "news-media-and-associations", slug: "news-media-and-associations", name: "News, Media & Associations", level: 1, parentId: "", order: 18 },
  { id: "news-and-media", slug: "news-and-media", name: "News & Media", level: 2, parentId: "news-media-and-associations", order: 1 },
  { id: "industry-associations", slug: "industry-associations", name: "Industry Associations", level: 2, parentId: "news-media-and-associations", order: 2 },
  { id: "standards-bodies", slug: "standards-bodies", name: "Standards Bodies", level: 2, parentId: "news-media-and-associations", order: 3 },

  // ── Renewables & Energy Storage (L1) ──────────────────────────────────
  // Added deliberately as its own sheet rather than folded into Sustainability:
  // ethanol blending, SATAT/CBG and the Green Hydrogen Mission are creating
  // storage requirements that differ materially from conventional hydrocarbons
  // (seal materials, coatings, corrosion behaviour, containment). Companies
  // specialising in exactly that need somewhere to land.
  { id: "renewables-and-energy-storage", slug: "renewables-and-energy-storage", name: "Renewables & Energy Storage", level: 1, parentId: "", order: 19 },
  { id: "solar-power-systems", slug: "solar-power-systems", name: "Solar Power Systems", level: 2, parentId: "renewables-and-energy-storage", order: 1 },
  { id: "bess-systems", slug: "bess-systems", name: "Battery Energy Storage (BESS)", level: 2, parentId: "renewables-and-energy-storage", order: 2 },
  { id: "hydrogen-storage-and-handling", slug: "hydrogen-storage-and-handling", name: "Hydrogen Storage & Handling", level: 2, parentId: "renewables-and-energy-storage", order: 3 },
  { id: "ammonia-storage-and-handling", slug: "ammonia-storage-and-handling", name: "Ammonia Storage & Handling", level: 2, parentId: "renewables-and-energy-storage", order: 4 },
  { id: "biofuel-and-ethanol-storage-systems", slug: "biofuel-and-ethanol-storage-systems", name: "Biofuel & Ethanol Storage Systems", level: 2, parentId: "renewables-and-energy-storage", order: 5 },
  { id: "cbg-and-biogas-infrastructure", slug: "cbg-and-biogas-infrastructure", name: "CBG & Biogas Infrastructure", level: 2, parentId: "renewables-and-energy-storage", order: 6 },
  { id: "carbon-capture-equipment", slug: "carbon-capture-equipment", name: "Carbon Capture Equipment", level: 2, parentId: "renewables-and-energy-storage", order: 7 },
  { id: "energy-efficiency-systems", slug: "energy-efficiency-systems", name: "Energy Efficiency Systems", level: 2, parentId: "renewables-and-energy-storage", order: 8 },

  // ── Inspection Equipment (L1) ─────────────────────────────────────────
  // The Asset Integrity sheet is entirely SERVICES — someone you hire. The
  // instruments themselves are a separate industry with separate vendors and
  // previously had no home anywhere in the tree.
  { id: "inspection-equipment", slug: "inspection-equipment", name: "Inspection Equipment", level: 1, parentId: "", order: 20 },
  { id: "ndt-equipment", slug: "ndt-equipment", name: "NDT Equipment", level: 2, parentId: "inspection-equipment", order: 1 },
  { id: "ultrasonic-flaw-detectors", slug: "ultrasonic-flaw-detectors", name: "Ultrasonic Flaw Detectors", level: 3, parentId: "ndt-equipment", order: 1 },
  { id: "thickness-gauges", slug: "thickness-gauges", name: "Thickness Gauges", level: 3, parentId: "ndt-equipment", order: 2 },
  { id: "phased-array-and-tofd", slug: "phased-array-and-tofd", name: "Phased Array & TOFD", level: 3, parentId: "ndt-equipment", order: 3 },
  { id: "tank-floor-scanners", slug: "tank-floor-scanners", name: "Tank Floor Scanners (MFL)", level: 2, parentId: "inspection-equipment", order: 2 },
  { id: "radiographic-equipment", slug: "radiographic-equipment", name: "Radiographic Equipment", level: 2, parentId: "inspection-equipment", order: 3 },
  { id: "weld-inspection-equipment", slug: "weld-inspection-equipment", name: "Weld Inspection Equipment", level: 2, parentId: "inspection-equipment", order: 4 },
  { id: "acoustic-emission-systems", slug: "acoustic-emission-systems", name: "Acoustic Emission Systems", level: 2, parentId: "inspection-equipment", order: 5 },
  { id: "borescopes-and-visual-inspection", slug: "borescopes-and-visual-inspection", name: "Borescopes & Visual Inspection", level: 2, parentId: "inspection-equipment", order: 6 },
  { id: "inspection-drones-and-crawlers", slug: "inspection-drones-and-crawlers", name: "Inspection Drones & Crawlers", level: 2, parentId: "inspection-equipment", order: 7 },

  // Contractor Compliance: distinct from Regulatory Compliance (fire-safety-
  // and-environment L2) — that's about complying with government regulation;
  // this is third-party verification of OTHER contractors' safety records,
  // insurance and certifications before site access (the ISNetworld/Avetta/
  // Veriforce category). Filed under Training & Workforce alongside
  // Certification Bodies since both are third-party verification services,
  // not under Fire/Safety/Environment where Regulatory Compliance lives.
  { id: "contractor-compliance", slug: "contractor-compliance", name: "Contractor Compliance", level: 2, parentId: "training-and-workforce", order: 10 },

  // ── Rental (L1) ──────────────────────────────────────────────────────
  // Equipment rental (scaffolding, generators, cranes, pumps, temporary
  // storage) is a genuinely distinct business model from equipment
  // manufacture/sale, which is what the rest of the tree assumes — a
  // turnaround/maintenance project routinely runs on rented, not owned,
  // equipment. Previously had no home anywhere in the tree.
  { id: "rental", slug: "rental", name: "Rental", level: 1, parentId: "", order: 21 },
  { id: "scaffolding-rental", slug: "scaffolding-rental", name: "Scaffolding Rental", level: 2, parentId: "rental", order: 1 },
  { id: "generator-and-power-equipment-rental", slug: "generator-and-power-equipment-rental", name: "Generator & Power Equipment Rental", level: 2, parentId: "rental", order: 2 },
  { id: "crane-and-lifting-equipment-rental", slug: "crane-and-lifting-equipment-rental", name: "Crane & Lifting Equipment Rental", level: 2, parentId: "rental", order: 3 },
  { id: "pump-and-compressor-rental", slug: "pump-and-compressor-rental", name: "Pump & Compressor Rental", level: 2, parentId: "rental", order: 4 },
  { id: "epcm-services", slug: "epcm-services", name: "EPCM Services", level: 2, parentId: "engineering-and-construction", order: 2 },
  { id: "ball-valves", slug: "ball-valves", name: "Ball Valves", level: 3, parentId: "valves", order: 1 },
  { id: "gate-globe-and-check-valves", slug: "gate-globe-and-check-valves", name: "Gate, Globe & Check Valves", level: 3, parentId: "valves", order: 2 },
  { id: "butterfly-valves", slug: "butterfly-valves", name: "Butterfly Valves", level: 3, parentId: "valves", order: 3 },
  { id: "control-valves", slug: "control-valves", name: "Control Valves", level: 3, parentId: "valves", order: 4 },
  { id: "safety-and-pressure-relief-valves", slug: "safety-and-pressure-relief-valves", name: "Safety & Pressure Relief Valves", level: 3, parentId: "valves", order: 5 },
  { id: "severe-service-valves", slug: "severe-service-valves", name: "Severe Service Valves", level: 3, parentId: "valves", order: 6 },
  { id: "cryogenic-valves", slug: "cryogenic-valves", name: "Cryogenic Valves", level: 3, parentId: "valves", order: 7 },
  { id: "double-block-and-bleed-valves", slug: "double-block-and-bleed-valves", name: "Double Block & Bleed Valves", level: 3, parentId: "valves", order: 8 },
  { id: "instrumentation-and-manifold-valves", slug: "instrumentation-and-manifold-valves", name: "Instrumentation & Manifold Valves", level: 3, parentId: "valves", order: 9 },
  { id: "shell-and-tube-heat-exchangers", slug: "shell-and-tube-heat-exchangers", name: "Shell & Tube Heat Exchangers", level: 3, parentId: "heat-exchangers", order: 1 },
  { id: "air-cooled-heat-exchangers", slug: "air-cooled-heat-exchangers", name: "Air-Cooled Heat Exchangers", level: 3, parentId: "heat-exchangers", order: 2 },
  { id: "plate-heat-exchangers", slug: "plate-heat-exchangers", name: "Plate Heat Exchangers", level: 3, parentId: "heat-exchangers", order: 3 },
  { id: "waste-heat-recovery-units", slug: "waste-heat-recovery-units", name: "Waste Heat Recovery Units", level: 3, parentId: "heat-exchangers", order: 4 },
  { id: "steam-traps", slug: "steam-traps", name: "Steam Traps", level: 2, parentId: "flow-and-transfer-equipment", order: 25 },
  { id: "strainers-and-line-protection", slug: "strainers-and-line-protection", name: "Strainers & Line Protection", level: 2, parentId: "flow-and-transfer-equipment", order: 26 },
  { id: "spectacle-blinds-and-line-blinds", slug: "spectacle-blinds-and-line-blinds", name: "Spectacle Blinds & Line Blinds", level: 2, parentId: "flow-and-transfer-equipment", order: 27 },
  { id: "expansion-joints-and-bellows", slug: "expansion-joints-and-bellows", name: "Expansion Joints & Bellows", level: 2, parentId: "flow-and-transfer-equipment", order: 28 },
  { id: "turnaround-and-shutdown-services", slug: "turnaround-and-shutdown-services", name: "Turnaround & Shutdown Services", level: 2, parentId: "asset-integrity-and-inspection", order: 20 },
  { id: "chemical-cleaning-and-hydrojetting", slug: "chemical-cleaning-and-hydrojetting", name: "Chemical Cleaning & Hydrojetting", level: 2, parentId: "asset-integrity-and-inspection", order: 21 },
  { id: "on-site-machining", slug: "on-site-machining", name: "On-Site Machining", level: 2, parentId: "asset-integrity-and-inspection", order: 22 },
  { id: "valve-overhaul-and-testing", slug: "valve-overhaul-and-testing", name: "Valve Overhaul & Testing", level: 2, parentId: "asset-integrity-and-inspection", order: 23 },
  { id: "risk-based-inspection", slug: "risk-based-inspection", name: "Risk-Based Inspection (RBI)", level: 2, parentId: "asset-integrity-and-inspection", order: 24 },
  { id: "fitness-for-service-and-remaining-life", slug: "fitness-for-service-and-remaining-life", name: "Fitness-for-Service & Remaining Life", level: 2, parentId: "asset-integrity-and-inspection", order: 25 },
  { id: "positive-material-identification", slug: "positive-material-identification", name: "Positive Material Identification (PMI)", level: 2, parentId: "asset-integrity-and-inspection", order: 26 },
  { id: "failure-analysis-and-metallurgical-testing", slug: "failure-analysis-and-metallurgical-testing", name: "Failure Analysis & Metallurgical Testing", level: 2, parentId: "asset-integrity-and-inspection", order: 27 },
  { id: "online-leak-sealing", slug: "online-leak-sealing", name: "Online Leak Sealing", level: 2, parentId: "asset-integrity-and-inspection", order: 28 },
  { id: "pipeline-pigging-and-intervention", slug: "pipeline-pigging-and-intervention", name: "Pipeline Pigging & Intervention", level: 2, parentId: "asset-integrity-and-inspection", order: 29 },
  { id: "pipe-supports-and-hangers", slug: "pipe-supports-and-hangers", name: "Pipe Supports & Hangers", level: 2, parentId: "industrial-supplies-mro", order: 5 },
  { id: "offshore-and-subsea-systems", slug: "offshore-and-subsea-systems", name: "Offshore & Subsea Systems", level: 1, parentId: "", order: 99 },
  { id: "subsea-production-systems", slug: "subsea-production-systems", name: "Subsea Production Systems", level: 2, parentId: "offshore-and-subsea-systems", order: 2 },
  { id: "subsea-trees-and-wellheads", slug: "subsea-trees-and-wellheads", name: "Subsea Trees & Wellheads", level: 3, parentId: "subsea-production-systems", order: 1 },
  { id: "subsea-manifolds-and-plet-plem", slug: "subsea-manifolds-and-plet-plem", name: "Subsea Manifolds & PLET/PLEM", level: 3, parentId: "subsea-production-systems", order: 2 },
  { id: "subsea-control-systems", slug: "subsea-control-systems", name: "Subsea Control Systems", level: 3, parentId: "subsea-production-systems", order: 3 },
  { id: "surf-umbilicals-risers-flowlines", slug: "surf-umbilicals-risers-flowlines", name: "SURF (Umbilicals, Risers & Flowlines)", level: 2, parentId: "offshore-and-subsea-systems", order: 3 },
  { id: "umbilicals-and-flying-leads", slug: "umbilicals-and-flying-leads", name: "Umbilicals & Flying Leads", level: 3, parentId: "surf-umbilicals-risers-flowlines", order: 1 },
  { id: "flexible-and-rigid-risers", slug: "flexible-and-rigid-risers", name: "Flexible & Rigid Risers", level: 3, parentId: "surf-umbilicals-risers-flowlines", order: 2 },
  { id: "subsea-flowlines", slug: "subsea-flowlines", name: "Subsea Flowlines", level: 3, parentId: "surf-umbilicals-risers-flowlines", order: 3 },
  { id: "mooring-systems", slug: "mooring-systems", name: "Mooring Systems", level: 2, parentId: "offshore-and-subsea-systems", order: 4 },
  { id: "turret-mooring-systems", slug: "turret-mooring-systems", name: "Turret Mooring Systems", level: 3, parentId: "mooring-systems", order: 1 },
  { id: "mooring-chains-and-connectors", slug: "mooring-chains-and-connectors", name: "Mooring Chains & Connectors", level: 3, parentId: "mooring-systems", order: 2 },
  { id: "anchors-and-mooring-hardware", slug: "anchors-and-mooring-hardware", name: "Anchors & Mooring Hardware", level: 3, parentId: "mooring-systems", order: 3 },
  { id: "offshore-structures-and-fabrication", slug: "offshore-structures-and-fabrication", name: "Offshore Structures & Fabrication", level: 2, parentId: "offshore-and-subsea-systems", order: 5 },
  { id: "jackets-and-substructures", slug: "jackets-and-substructures", name: "Jackets & Substructures", level: 3, parentId: "offshore-structures-and-fabrication", order: 1 },
  { id: "topsides-and-modules", slug: "topsides-and-modules", name: "Topsides & Modules", level: 3, parentId: "offshore-structures-and-fabrication", order: 2 },
  { id: "offshore-installation-and-epcic", slug: "offshore-installation-and-epcic", name: "Offshore Installation & EPCIC", level: 2, parentId: "offshore-and-subsea-systems", order: 6 },
  { id: "subsea-services-and-intervention", slug: "subsea-services-and-intervention", name: "Subsea Services & Intervention", level: 2, parentId: "offshore-and-subsea-systems", order: 7 },
  { id: "rov-services", slug: "rov-services", name: "ROV Services", level: 3, parentId: "subsea-services-and-intervention", order: 1 },
  { id: "commercial-diving", slug: "commercial-diving", name: "Commercial Diving", level: 3, parentId: "subsea-services-and-intervention", order: 2 },
  { id: "offshore-support-vessels", slug: "offshore-support-vessels", name: "Offshore Support Vessels", level: 2, parentId: "offshore-and-subsea-systems", order: 8 },
  { id: "naval-architecture-and-marine-engineering", slug: "naval-architecture-and-marine-engineering", name: "Naval Architecture & Marine Engineering", level: 2, parentId: "offshore-and-subsea-systems", order: 9 },
  { id: "shipbuilding", slug: "shipbuilding", name: "Shipbuilding", level: 2, parentId: "offshore-and-subsea-systems", order: 10 },
  { id: "ship-repair-and-conversion", slug: "ship-repair-and-conversion", name: "Ship Repair & Conversion", level: 2, parentId: "offshore-and-subsea-systems", order: 11 },
  { id: "process-plant-equipment", slug: "process-plant-equipment", name: "Process Plant Equipment", level: 1, parentId: "", order: 99 },
  { id: "pressure-vessels-and-reactors", slug: "pressure-vessels-and-reactors", name: "Pressure Vessels & Reactors", level: 2, parentId: "process-plant-equipment", order: 1 },
  { id: "distillation-columns-and-tower-internals", slug: "distillation-columns-and-tower-internals", name: "Distillation Columns & Tower Internals", level: 2, parentId: "process-plant-equipment", order: 2 },
  { id: "trays-and-packing", slug: "trays-and-packing", name: "Trays & Packing", level: 3, parentId: "distillation-columns-and-tower-internals", order: 1 },
  { id: "reactor-internals-and-fcc-cyclones", slug: "reactor-internals-and-fcc-cyclones", name: "Reactor Internals & FCC Cyclones", level: 3, parentId: "distillation-columns-and-tower-internals", order: 2 },
  { id: "fired-heaters-and-process-furnaces", slug: "fired-heaters-and-process-furnaces", name: "Fired Heaters & Process Furnaces", level: 2, parentId: "process-plant-equipment", order: 3 },
  { id: "burners-and-low-nox-combustion", slug: "burners-and-low-nox-combustion", name: "Burners & Low-NOx Combustion", level: 3, parentId: "fired-heaters-and-process-furnaces", order: 1 },
  { id: "flare-systems", slug: "flare-systems", name: "Flare Systems", level: 2, parentId: "process-plant-equipment", order: 4 },
  { id: "flare-tips-and-stacks", slug: "flare-tips-and-stacks", name: "Flare Tips & Stacks", level: 3, parentId: "flare-systems", order: 1 },
  { id: "flare-gas-recovery", slug: "flare-gas-recovery", name: "Flare Gas Recovery", level: 3, parentId: "flare-systems", order: 2 },
  { id: "sulphur-recovery-units", slug: "sulphur-recovery-units", name: "Sulphur Recovery Units (SRU/TGT)", level: 2, parentId: "process-plant-equipment", order: 5 },
  { id: "sulphur-degassing-and-handling", slug: "sulphur-degassing-and-handling", name: "Sulphur Degassing & Handling", level: 3, parentId: "sulphur-recovery-units", order: 1 },
  { id: "amine-and-gas-treating-systems", slug: "amine-and-gas-treating-systems", name: "Amine & Gas Treating Systems", level: 2, parentId: "process-plant-equipment", order: 6 },
  { id: "sour-water-stripping", slug: "sour-water-stripping", name: "Sour Water Stripping", level: 3, parentId: "amine-and-gas-treating-systems", order: 1 },
  { id: "hydrogen-generation", slug: "hydrogen-generation", name: "Hydrogen Generation", level: 2, parentId: "process-plant-equipment", order: 7 },
  { id: "smr-and-reformer-equipment", slug: "smr-and-reformer-equipment", name: "SMR & Reformer Equipment", level: 3, parentId: "hydrogen-generation", order: 1 },
  { id: "psa-and-gas-purification", slug: "psa-and-gas-purification", name: "PSA & Gas Purification", level: 3, parentId: "hydrogen-generation", order: 2 },
  { id: "desalters-and-electrostatic-separation", slug: "desalters-and-electrostatic-separation", name: "Desalters & Electrostatic Separation", level: 2, parentId: "process-plant-equipment", order: 8 },
  { id: "separators-scrubbers-and-coalescers", slug: "separators-scrubbers-and-coalescers", name: "Separators, Scrubbers & Coalescers", level: 2, parentId: "process-plant-equipment", order: 9 },
  { id: "coke-drums-and-delayed-coking-equipment", slug: "coke-drums-and-delayed-coking-equipment", name: "Coke Drums & Delayed Coking Equipment", level: 2, parentId: "process-plant-equipment", order: 10 },
  { id: "incinerators-and-thermal-oxidizers", slug: "incinerators-and-thermal-oxidizers", name: "Incinerators & Thermal Oxidizers", level: 2, parentId: "process-plant-equipment", order: 11 },
  { id: "package-units-and-process-skids", slug: "package-units-and-process-skids", name: "Package Units & Process Skids", level: 2, parentId: "process-plant-equipment", order: 12 },
  { id: "upstream-and-drilling", slug: "upstream-and-drilling", name: "Upstream & Drilling", level: 1, parentId: "", order: 99 },
  { id: "drilling-contractors", slug: "drilling-contractors", name: "Drilling Contractors", level: 2, parentId: "upstream-and-drilling", order: 1 },
  { id: "onshore-drilling", slug: "onshore-drilling", name: "Onshore Drilling", level: 3, parentId: "drilling-contractors", order: 1 },
  { id: "offshore-drilling", slug: "offshore-drilling", name: "Offshore Drilling", level: 3, parentId: "drilling-contractors", order: 2 },
  { id: "directional-drilling-and-mwd-lwd", slug: "directional-drilling-and-mwd-lwd", name: "Directional Drilling & MWD/LWD", level: 2, parentId: "upstream-and-drilling", order: 2 },
  { id: "drilling-fluids-and-mud-systems", slug: "drilling-fluids-and-mud-systems", name: "Drilling Fluids & Mud Systems", level: 2, parentId: "upstream-and-drilling", order: 3 },
  { id: "mud-logging-and-wellsite-geology", slug: "mud-logging-and-wellsite-geology", name: "Mud Logging & Wellsite Geology", level: 2, parentId: "upstream-and-drilling", order: 4 },
  { id: "well-completion-and-intervention", slug: "well-completion-and-intervention", name: "Well Completion & Intervention", level: 2, parentId: "upstream-and-drilling", order: 5 },
  { id: "cementing-and-stimulation", slug: "cementing-and-stimulation", name: "Cementing & Stimulation", level: 2, parentId: "upstream-and-drilling", order: 6 },
  { id: "wellheads-and-surface-trees", slug: "wellheads-and-surface-trees", name: "Wellheads & Surface Trees", level: 2, parentId: "upstream-and-drilling", order: 7 },
  { id: "drill-bits-and-downhole-tools", slug: "drill-bits-and-downhole-tools", name: "Drill Bits & Downhole Tools", level: 2, parentId: "upstream-and-drilling", order: 8 },
  { id: "seismic-and-geophysical-services", slug: "seismic-and-geophysical-services", name: "Seismic & Geophysical Services", level: 2, parentId: "upstream-and-drilling", order: 9 },
  { id: "core-analysis-and-reservoir-services", slug: "core-analysis-and-reservoir-services", name: "Core Analysis & Reservoir Services", level: 2, parentId: "upstream-and-drilling", order: 10 },
  { id: "workover-and-well-servicing", slug: "workover-and-well-servicing", name: "Workover & Well Servicing", level: 2, parentId: "upstream-and-drilling", order: 11 },
  { id: "coiled-tubing-and-pressure-pumping", slug: "coiled-tubing-and-pressure-pumping", name: "Coiled Tubing & Pressure Pumping", level: 2, parentId: "upstream-and-drilling", order: 12 },
  { id: "production-chemicals-upstream", slug: "production-chemicals-upstream", name: "Production Chemicals (Upstream)", level: 2, parentId: "upstream-and-drilling", order: 13 },
];
