// Auto-generated from Tankonomics_Categories_Proposed.xlsx (18 L1 · 224 L2).
// Master company-category tree. Doc id === slug (stable, cross-app join key).
// Seed via Admin → Companies tab → "Seed master tree" (handleSeedCategories).

export interface CategorySeedNode {
  id: string;        // === slug; used as the Firestore document id
  slug: string;
  name: string;
  level: 1 | 2;
  parentId: string;  // "" for level 1; parent slug for level 2
  order: number;
}

export const CATEGORY_SEED: CategorySeedNode[] = [
  { id: "storage-terminals", slug: "storage-terminals", name: "Storage Terminals", level: 1, parentId: "", order: 1 },
  { id: "independent-terminals", slug: "independent-terminals", name: "Independent Terminals", level: 2, parentId: "storage-terminals", order: 1 },
  { id: "captive-terminals", slug: "captive-terminals", name: "Captive Terminals", level: 2, parentId: "storage-terminals", order: 2 },
  { id: "process-industries", slug: "process-industries", name: "Process Industries", level: 1, parentId: "", order: 2 },
  { id: "refineries", slug: "refineries", name: "Refineries", level: 2, parentId: "process-industries", order: 1 },
  { id: "petrochemicals", slug: "petrochemicals", name: "Petrochemicals", level: 2, parentId: "process-industries", order: 2 },
  { id: "chemicals", slug: "chemicals", name: "Chemicals", level: 2, parentId: "process-industries", order: 3 },
  { id: "fertilisers", slug: "fertilisers", name: "Fertilisers", level: 2, parentId: "process-industries", order: 4 },
  { id: "industrial-gases", slug: "industrial-gases", name: "Industrial Gases", level: 2, parentId: "process-industries", order: 5 },
  { id: "gas-processing-lng-lpg", slug: "gas-processing-lng-lpg", name: "Gas Processing (LNG/LPG)", level: 2, parentId: "process-industries", order: 6 },
  { id: "biofuels-and-ethanol", slug: "biofuels-and-ethanol", name: "Biofuels & Ethanol", level: 2, parentId: "process-industries", order: 7 },
  { id: "edible-oils-and-fats", slug: "edible-oils-and-fats", name: "Edible Oils & Fats", level: 2, parentId: "process-industries", order: 8 },
  { id: "food-and-beverage-processing", slug: "food-and-beverage-processing", name: "Food & Beverage Processing", level: 2, parentId: "process-industries", order: 9 },
  { id: "pharmaceuticals", slug: "pharmaceuticals", name: "Pharmaceuticals", level: 2, parentId: "process-industries", order: 10 },
  { id: "lubricants-and-bitumen", slug: "lubricants-and-bitumen", name: "Lubricants & Bitumen", level: 2, parentId: "process-industries", order: 11 },
  { id: "natural-resources-and-upstream", slug: "natural-resources-and-upstream", name: "Natural Resources & Upstream", level: 1, parentId: "", order: 3 },
  { id: "oil-and-gas-exploration", slug: "oil-and-gas-exploration", name: "Oil & Gas Exploration", level: 2, parentId: "natural-resources-and-upstream", order: 1 },
  { id: "offshore-production", slug: "offshore-production", name: "Offshore Production", level: 2, parentId: "natural-resources-and-upstream", order: 2 },
  { id: "lng-production", slug: "lng-production", name: "LNG Production", level: 2, parentId: "natural-resources-and-upstream", order: 3 },
  { id: "mining-and-minerals", slug: "mining-and-minerals", name: "Mining & Minerals", level: 2, parentId: "natural-resources-and-upstream", order: 4 },
  { id: "coal", slug: "coal", name: "Coal", level: 2, parentId: "natural-resources-and-upstream", order: 5 },
  { id: "iron-ore", slug: "iron-ore", name: "Iron Ore", level: 2, parentId: "natural-resources-and-upstream", order: 6 },
  { id: "critical-minerals", slug: "critical-minerals", name: "Critical Minerals", level: 2, parentId: "natural-resources-and-upstream", order: 7 },
  { id: "engineering-and-construction", slug: "engineering-and-construction", name: "Engineering & Construction", level: 1, parentId: "", order: 4 },
  { id: "epc-contractors", slug: "epc-contractors", name: "EPC Contractors", level: 2, parentId: "engineering-and-construction", order: 1 },
  { id: "tank-construction", slug: "tank-construction", name: "Tank Construction", level: 2, parentId: "engineering-and-construction", order: 2 },
  { id: "tank-engineering", slug: "tank-engineering", name: "Tank Engineering", level: 2, parentId: "engineering-and-construction", order: 3 },
  { id: "civil-and-structural-engineering", slug: "civil-and-structural-engineering", name: "Civil & Structural Engineering", level: 2, parentId: "engineering-and-construction", order: 4 },
  { id: "foundation-contractors", slug: "foundation-contractors", name: "Foundation Contractors", level: 2, parentId: "engineering-and-construction", order: 5 },
  { id: "piping-contractors", slug: "piping-contractors", name: "Piping Contractors", level: 2, parentId: "engineering-and-construction", order: 6 },
  { id: "mechanical-contractors", slug: "mechanical-contractors", name: "Mechanical Contractors", level: 2, parentId: "engineering-and-construction", order: 7 },
  { id: "electrical-contractors", slug: "electrical-contractors", name: "Electrical Contractors", level: 2, parentId: "engineering-and-construction", order: 8 },
  { id: "instrumentation-contractors", slug: "instrumentation-contractors", name: "Instrumentation Contractors", level: 2, parentId: "engineering-and-construction", order: 9 },
  { id: "insulation-contractors", slug: "insulation-contractors", name: "Insulation Contractors", level: 2, parentId: "engineering-and-construction", order: 10 },
  { id: "painting-and-coating-contractors", slug: "painting-and-coating-contractors", name: "Painting & Coating Contractors", level: 2, parentId: "engineering-and-construction", order: 11 },
  { id: "scaffolding-services", slug: "scaffolding-services", name: "Scaffolding Services", level: 2, parentId: "engineering-and-construction", order: 12 },
  { id: "industrial-flooring", slug: "industrial-flooring", name: "Industrial Flooring", level: 2, parentId: "engineering-and-construction", order: 13 },
  { id: "roofing-systems", slug: "roofing-systems", name: "Roofing Systems", level: 2, parentId: "engineering-and-construction", order: 14 },
  { id: "demolition-and-decommissioning", slug: "demolition-and-decommissioning", name: "Demolition & Decommissioning", level: 2, parentId: "engineering-and-construction", order: 15 },
  { id: "heavy-engineering-and-fabrication", slug: "heavy-engineering-and-fabrication", name: "Heavy Engineering & Fabrication", level: 2, parentId: "engineering-and-construction", order: 16 },
  { id: "tank-maintenance", slug: "tank-maintenance", name: "Tank Maintenance", level: 2, parentId: "engineering-and-construction", order: 17 },
  { id: "surface-preparation-and-blasting", slug: "surface-preparation-and-blasting", name: "Surface Preparation & Blasting", level: 2, parentId: "engineering-and-construction", order: 18 },
  { id: "tank-systems-and-equipment", slug: "tank-systems-and-equipment", name: "Tank Systems & Equipment", level: 1, parentId: "", order: 5 },
  { id: "tank-gauging", slug: "tank-gauging", name: "Tank Gauging", level: 2, parentId: "tank-systems-and-equipment", order: 1 },
  // ── Level 3 ────────────────────────────────────────────────────────────
  // Tank Gauging is the first L2 to gain sub-types. Custody transfer accuracy
  // is the commercial core of a terminal, and radar / servo / temperature /
  // interface instruments are genuinely different purchases from different
  // vendors — a single flat "Tank Gauging" node hid that.
  //
  // Selecting the L2 remains INCLUSIVE of everything below it, so a company
  // tagged only "radar-level-gauges" still appears under Tank Gauging.
  { id: "radar-level-gauges", slug: "radar-level-gauges", name: "Radar Level Gauges", level: 3, parentId: "tank-gauging", order: 1 },
  { id: "servo-gauges", slug: "servo-gauges", name: "Servo Gauges", level: 3, parentId: "tank-gauging", order: 2 },
  { id: "temperature-measurement-mtt", slug: "temperature-measurement-mtt", name: "Temperature Measurement (MTT)", level: 3, parentId: "tank-gauging", order: 3 },
  { id: "water-interface-detection", slug: "water-interface-detection", name: "Water Interface Detection", level: 3, parentId: "tank-gauging", order: 4 },
  { id: "manual-gauging-equipment", slug: "manual-gauging-equipment", name: "Manual Gauging Equipment", level: 3, parentId: "tank-gauging", order: 5 },
  { id: "tank-sampling-systems", slug: "tank-sampling-systems", name: "Tank Sampling Systems", level: 3, parentId: "tank-gauging", order: 6 },
  { id: "rim-seals", slug: "rim-seals", name: "Rim Seals", level: 2, parentId: "tank-systems-and-equipment", order: 2 },
  { id: "seal-fittings", slug: "seal-fittings", name: "Seal Fittings", level: 2, parentId: "tank-systems-and-equipment", order: 3 },
  { id: "floating-roof-systems", slug: "floating-roof-systems", name: "Floating Roof Systems", level: 2, parentId: "tank-systems-and-equipment", order: 4 },
  { id: "internal-floating-roofs", slug: "internal-floating-roofs", name: "Internal Floating Roofs", level: 2, parentId: "tank-systems-and-equipment", order: 5 },
  { id: "aluminium-dome-roofs", slug: "aluminium-dome-roofs", name: "Aluminium Dome Roofs", level: 2, parentId: "tank-systems-and-equipment", order: 6 },
  { id: "gauge-hatches", slug: "gauge-hatches", name: "Gauge Hatches", level: 2, parentId: "tank-systems-and-equipment", order: 7 },
  { id: "roof-drains", slug: "roof-drains", name: "Roof Drains", level: 2, parentId: "tank-systems-and-equipment", order: 8 },
  { id: "foam-chambers", slug: "foam-chambers", name: "Foam Chambers", level: 2, parentId: "tank-systems-and-equipment", order: 9 },
  { id: "foam-dams", slug: "foam-dams", name: "Foam Dams", level: 2, parentId: "tank-systems-and-equipment", order: 10 },
  { id: "nozzles-and-manways", slug: "nozzles-and-manways", name: "Nozzles & Manways", level: 2, parentId: "tank-systems-and-equipment", order: 11 },
  { id: "mixers-and-agitators", slug: "mixers-and-agitators", name: "Mixers & Agitators", level: 2, parentId: "tank-systems-and-equipment", order: 12 },
  { id: "heating-systems", slug: "heating-systems", name: "Heating Systems", level: 2, parentId: "tank-systems-and-equipment", order: 13 },
  { id: "tank-blanketing", slug: "tank-blanketing", name: "Tank Blanketing", level: 2, parentId: "tank-systems-and-equipment", order: 14 },
  { id: "vapour-recovery-units-vru", slug: "vapour-recovery-units-vru", name: "Vapour Recovery Units (VRU)", level: 2, parentId: "tank-systems-and-equipment", order: 15 },
  { id: "pressure-vacuum-vents", slug: "pressure-vacuum-vents", name: "Pressure/Vacuum Vents", level: 2, parentId: "tank-systems-and-equipment", order: 16 },
  { id: "emergency-vents", slug: "emergency-vents", name: "Emergency Vents", level: 2, parentId: "tank-systems-and-equipment", order: 17 },
  { id: "flame-arresters", slug: "flame-arresters", name: "Flame Arresters", level: 2, parentId: "tank-systems-and-equipment", order: 18 },
  { id: "breather-valves", slug: "breather-valves", name: "Breather Valves", level: 2, parentId: "tank-systems-and-equipment", order: 19 },
  { id: "conservation-vents", slug: "conservation-vents", name: "Conservation Vents", level: 2, parentId: "tank-systems-and-equipment", order: 20 },
  { id: "floating-suction-systems", slug: "floating-suction-systems", name: "Floating Suction Systems", level: 2, parentId: "tank-systems-and-equipment", order: 21 },
  { id: "water-draw-off-systems", slug: "water-draw-off-systems", name: "Water Draw-Off Systems", level: 2, parentId: "tank-systems-and-equipment", order: 22 },
  { id: "overfill-protection", slug: "overfill-protection", name: "Overfill Protection", level: 2, parentId: "tank-systems-and-equipment", order: 23 },
  { id: "hydraulic-jacking-and-automatic-welding-systems", slug: "hydraulic-jacking-and-automatic-welding-systems", name: "Hydraulic Jacking & Automatic Welding Systems", level: 2, parentId: "tank-systems-and-equipment", order: 24 },
  { id: "bolted-steel-tanks", slug: "bolted-steel-tanks", name: "Bolted Steel Tanks", level: 2, parentId: "tank-systems-and-equipment", order: 25 },
  { id: "industrial-gratings", slug: "industrial-gratings", name: "Industrial Gratings", level: 2, parentId: "tank-systems-and-equipment", order: 26 },
  { id: "industrial-ladders", slug: "industrial-ladders", name: "Industrial Ladders", level: 2, parentId: "tank-systems-and-equipment", order: 27 },
  { id: "industrial-platforms", slug: "industrial-platforms", name: "Industrial Platforms", level: 2, parentId: "tank-systems-and-equipment", order: 28 },
  { id: "cranes-and-lifting-equipment", slug: "cranes-and-lifting-equipment", name: "Cranes & Lifting Equipment", level: 2, parentId: "tank-systems-and-equipment", order: 29 },
  { id: "blasting-and-painting-equipment", slug: "blasting-and-painting-equipment", name: "Blasting & Painting Equipment", level: 2, parentId: "tank-systems-and-equipment", order: 30 },
  { id: "flow-and-transfer-equipment", slug: "flow-and-transfer-equipment", name: "Flow & Transfer Equipment", level: 1, parentId: "", order: 6 },
  { id: "pumps", slug: "pumps", name: "Pumps", level: 2, parentId: "flow-and-transfer-equipment", order: 1 },
  { id: "compressors", slug: "compressors", name: "Compressors", level: 2, parentId: "flow-and-transfer-equipment", order: 2 },
  { id: "blowers", slug: "blowers", name: "Blowers", level: 2, parentId: "flow-and-transfer-equipment", order: 3 },
  { id: "loading-pumps", slug: "loading-pumps", name: "Loading Pumps", level: 2, parentId: "flow-and-transfer-equipment", order: 4 },
  { id: "transfer-pumps", slug: "transfer-pumps", name: "Transfer Pumps", level: 2, parentId: "flow-and-transfer-equipment", order: 5 },
  { id: "metering-pumps", slug: "metering-pumps", name: "Metering Pumps", level: 2, parentId: "flow-and-transfer-equipment", order: 6 },
  { id: "valves", slug: "valves", name: "Valves", level: 2, parentId: "flow-and-transfer-equipment", order: 7 },
  { id: "actuators", slug: "actuators", name: "Actuators", level: 2, parentId: "flow-and-transfer-equipment", order: 8 },
  { id: "flow-meters", slug: "flow-meters", name: "Flow Meters", level: 2, parentId: "flow-and-transfer-equipment", order: 9 },
  { id: "custody-transfer-metering", slug: "custody-transfer-metering", name: "Custody Transfer Metering", level: 2, parentId: "flow-and-transfer-equipment", order: 10 },
  { id: "pigging-systems", slug: "pigging-systems", name: "Pigging Systems", level: 2, parentId: "flow-and-transfer-equipment", order: 11 },
  { id: "strainers", slug: "strainers", name: "Strainers", level: 2, parentId: "flow-and-transfer-equipment", order: 12 },
  { id: "expansion-joints", slug: "expansion-joints", name: "Expansion Joints", level: 2, parentId: "flow-and-transfer-equipment", order: 13 },
  { id: "flexible-hoses", slug: "flexible-hoses", name: "Flexible Hoses", level: 2, parentId: "flow-and-transfer-equipment", order: 14 },
  { id: "loading-arms", slug: "loading-arms", name: "Loading Arms", level: 2, parentId: "flow-and-transfer-equipment", order: 15 },
  { id: "marine-loading-arms", slug: "marine-loading-arms", name: "Marine Loading Arms", level: 2, parentId: "flow-and-transfer-equipment", order: 16 },
  { id: "truck-loading-systems", slug: "truck-loading-systems", name: "Truck Loading Systems", level: 2, parentId: "flow-and-transfer-equipment", order: 17 },
  { id: "rail-loading-systems", slug: "rail-loading-systems", name: "Rail Loading Systems", level: 2, parentId: "flow-and-transfer-equipment", order: 18 },
  { id: "instrumentation-and-automation", slug: "instrumentation-and-automation", name: "Instrumentation & Automation", level: 1, parentId: "", order: 7 },
  { id: "terminal-automation", slug: "terminal-automation", name: "Terminal Automation", level: 2, parentId: "instrumentation-and-automation", order: 1 },
  { id: "scada-systems", slug: "scada-systems", name: "SCADA Systems", level: 2, parentId: "instrumentation-and-automation", order: 2 },
  { id: "plc-and-dcs", slug: "plc-and-dcs", name: "PLC & DCS", level: 2, parentId: "instrumentation-and-automation", order: 3 },
  { id: "tank-inventory-systems", slug: "tank-inventory-systems", name: "Tank Inventory Systems", level: 2, parentId: "instrumentation-and-automation", order: 4 },
  { id: "remote-monitoring", slug: "remote-monitoring", name: "Remote Monitoring", level: 2, parentId: "instrumentation-and-automation", order: 5 },
  { id: "industrial-networking", slug: "industrial-networking", name: "Industrial Networking", level: 2, parentId: "instrumentation-and-automation", order: 6 },
  { id: "electrical-and-instrumentation", slug: "electrical-and-instrumentation", name: "Electrical & Instrumentation", level: 2, parentId: "instrumentation-and-automation", order: 7 },
  { id: "digital-ai-and-robotics", slug: "digital-ai-and-robotics", name: "Digital, AI & Robotics", level: 1, parentId: "", order: 8 },
  { id: "industrial-software", slug: "industrial-software", name: "Industrial Software", level: 2, parentId: "digital-ai-and-robotics", order: 1 },
  { id: "erp-solutions", slug: "erp-solutions", name: "ERP Solutions", level: 2, parentId: "digital-ai-and-robotics", order: 2 },
  { id: "cmms-eam", slug: "cmms-eam", name: "CMMS / EAM", level: 2, parentId: "digital-ai-and-robotics", order: 3 },
  { id: "gis-platforms", slug: "gis-platforms", name: "GIS Platforms", level: 2, parentId: "digital-ai-and-robotics", order: 4 },
  { id: "cloud-services", slug: "cloud-services", name: "Cloud Services", level: 2, parentId: "digital-ai-and-robotics", order: 5 },
  { id: "ai-and-analytics", slug: "ai-and-analytics", name: "AI & Analytics", level: 2, parentId: "digital-ai-and-robotics", order: 6 },
  { id: "data-integration", slug: "data-integration", name: "Data Integration", level: 2, parentId: "digital-ai-and-robotics", order: 7 },
  { id: "digital-twins", slug: "digital-twins", name: "Digital Twins", level: 2, parentId: "digital-ai-and-robotics", order: 8 },
  { id: "industrial-iot", slug: "industrial-iot", name: "Industrial IoT", level: 2, parentId: "digital-ai-and-robotics", order: 9 },
  { id: "predictive-maintenance", slug: "predictive-maintenance", name: "Predictive Maintenance", level: 2, parentId: "digital-ai-and-robotics", order: 10 },
  { id: "asset-performance-management", slug: "asset-performance-management", name: "Asset Performance Management", level: 2, parentId: "digital-ai-and-robotics", order: 11 },
  { id: "bim-services", slug: "bim-services", name: "BIM Services", level: 2, parentId: "digital-ai-and-robotics", order: 12 },
  { id: "digital-documentation", slug: "digital-documentation", name: "Digital Documentation", level: 2, parentId: "digital-ai-and-robotics", order: 13 },
  { id: "saas-providers", slug: "saas-providers", name: "SaaS Providers", level: 2, parentId: "digital-ai-and-robotics", order: 14 },
  { id: "cybersecurity", slug: "cybersecurity", name: "Cybersecurity", level: 2, parentId: "digital-ai-and-robotics", order: 15 },
  { id: "drone-and-robotic-inspection", slug: "drone-and-robotic-inspection", name: "Drone & Robotic Inspection", level: 2, parentId: "digital-ai-and-robotics", order: 16 },
  { id: "autonomous-inspection-robots", slug: "autonomous-inspection-robots", name: "Autonomous Inspection Robots", level: 2, parentId: "digital-ai-and-robotics", order: 17 },
  { id: "cctv-and-video-analytics", slug: "cctv-and-video-analytics", name: "CCTV & Video Analytics", level: 2, parentId: "digital-ai-and-robotics", order: 18 },
  { id: "laser-scanning-and-lidar", slug: "laser-scanning-and-lidar", name: "Laser Scanning & LiDAR", level: 2, parentId: "digital-ai-and-robotics", order: 19 },
  { id: "asset-integrity-and-inspection", slug: "asset-integrity-and-inspection", name: "Asset Integrity & Inspection", level: 1, parentId: "", order: 9 },
  { id: "tank-inspection", slug: "tank-inspection", name: "Tank Inspection", level: 2, parentId: "asset-integrity-and-inspection", order: 1 },
  { id: "non-destructive-testing-ndt", slug: "non-destructive-testing-ndt", name: "Non-Destructive Testing (NDT)", level: 2, parentId: "asset-integrity-and-inspection", order: 2 },
  { id: "corrosion-monitoring", slug: "corrosion-monitoring", name: "Corrosion Monitoring", level: 2, parentId: "asset-integrity-and-inspection", order: 3 },
  { id: "corrosion-protection", slug: "corrosion-protection", name: "Corrosion Protection", level: 2, parentId: "asset-integrity-and-inspection", order: 4 },
  { id: "cathodic-protection", slug: "cathodic-protection", name: "Cathodic Protection", level: 2, parentId: "asset-integrity-and-inspection", order: 5 },
  { id: "protective-coatings", slug: "protective-coatings", name: "Protective Coatings", level: 2, parentId: "asset-integrity-and-inspection", order: 6 },
  { id: "coatings-and-linings", slug: "coatings-and-linings", name: "Coatings & Linings", level: 2, parentId: "asset-integrity-and-inspection", order: 7 },
  { id: "refractory-services", slug: "refractory-services", name: "Refractory Services", level: 2, parentId: "asset-integrity-and-inspection", order: 8 },
  { id: "integrity-management", slug: "integrity-management", name: "Integrity Management", level: 2, parentId: "asset-integrity-and-inspection", order: 9 },
  { id: "risk-based-inspection-rbi", slug: "risk-based-inspection-rbi", name: "Risk-Based Inspection (RBI)", level: 2, parentId: "asset-integrity-and-inspection", order: 10 },
  { id: "fitness-for-service", slug: "fitness-for-service", name: "Fitness-for-Service", level: 2, parentId: "asset-integrity-and-inspection", order: 11 },
  { id: "life-extension", slug: "life-extension", name: "Life Extension", level: 2, parentId: "asset-integrity-and-inspection", order: 12 },
  { id: "tank-cleaning", slug: "tank-cleaning", name: "Tank Cleaning", level: 2, parentId: "asset-integrity-and-inspection", order: 13 },
  { id: "hydrotesting", slug: "hydrotesting", name: "Hydrotesting", level: 2, parentId: "asset-integrity-and-inspection", order: 14 },
  { id: "calibration-services", slug: "calibration-services", name: "Calibration Services", level: 2, parentId: "asset-integrity-and-inspection", order: 15 },
  { id: "rope-access-services", slug: "rope-access-services", name: "Rope Access Services", level: 2, parentId: "asset-integrity-and-inspection", order: 16 },
  { id: "leak-detection", slug: "leak-detection", name: "Leak Detection", level: 2, parentId: "asset-integrity-and-inspection", order: 17 },
  { id: "sludge-removal", slug: "sludge-removal", name: "Sludge Removal", level: 2, parentId: "asset-integrity-and-inspection", order: 18 },
  { id: "fire-safety-and-environment", slug: "fire-safety-and-environment", name: "Fire, Safety & Environment", level: 1, parentId: "", order: 10 },
  { id: "fire-protection", slug: "fire-protection", name: "Fire Protection", level: 2, parentId: "fire-safety-and-environment", order: 1 },
  { id: "fire-detection", slug: "fire-detection", name: "Fire Detection", level: 2, parentId: "fire-safety-and-environment", order: 2 },
  { id: "fire-fighting-foam", slug: "fire-fighting-foam", name: "Fire Fighting Foam", level: 2, parentId: "fire-safety-and-environment", order: 3 },
  { id: "rim-seal-fire-protection", slug: "rim-seal-fire-protection", name: "Rim Seal Fire Protection", level: 2, parentId: "fire-safety-and-environment", order: 4 },
  { id: "gas-detection", slug: "gas-detection", name: "Gas Detection", level: 2, parentId: "fire-safety-and-environment", order: 5 },
  { id: "emergency-shutdown-systems", slug: "emergency-shutdown-systems", name: "Emergency Shutdown Systems", level: 2, parentId: "fire-safety-and-environment", order: 6 },
  { id: "explosion-protection-atex", slug: "explosion-protection-atex", name: "Explosion Protection (ATEX)", level: 2, parentId: "fire-safety-and-environment", order: 7 },
  { id: "hazardous-area-equipment", slug: "hazardous-area-equipment", name: "Hazardous Area Equipment", level: 2, parentId: "fire-safety-and-environment", order: 8 },
  { id: "lightning-protection", slug: "lightning-protection", name: "Lightning Protection", level: 2, parentId: "fire-safety-and-environment", order: 9 },
  { id: "earthing-and-bonding", slug: "earthing-and-bonding", name: "Earthing & Bonding", level: 2, parentId: "fire-safety-and-environment", order: 10 },
  { id: "spill-containment", slug: "spill-containment", name: "Spill Containment", level: 2, parentId: "fire-safety-and-environment", order: 11 },
  { id: "environmental-monitoring", slug: "environmental-monitoring", name: "Environmental Monitoring", level: 2, parentId: "fire-safety-and-environment", order: 12 },
  { id: "occupational-safety", slug: "occupational-safety", name: "Occupational Safety", level: 2, parentId: "fire-safety-and-environment", order: 13 },
  { id: "hazop-and-risk-assessment", slug: "hazop-and-risk-assessment", name: "HAZOP & Risk Assessment", level: 2, parentId: "fire-safety-and-environment", order: 14 },
  { id: "functional-safety", slug: "functional-safety", name: "Functional Safety", level: 2, parentId: "fire-safety-and-environment", order: 15 },
  { id: "process-safety", slug: "process-safety", name: "Process Safety", level: 2, parentId: "fire-safety-and-environment", order: 16 },
  { id: "regulatory-compliance", slug: "regulatory-compliance", name: "Regulatory Compliance", level: 2, parentId: "fire-safety-and-environment", order: 17 },
  { id: "inspection-and-certification", slug: "inspection-and-certification", name: "Inspection & Certification", level: 2, parentId: "fire-safety-and-environment", order: 18 },
  { id: "materials-and-metallurgy", slug: "materials-and-metallurgy", name: "Materials & Metallurgy", level: 1, parentId: "", order: 11 },
  { id: "steel-manufacturers", slug: "steel-manufacturers", name: "Steel Manufacturers", level: 2, parentId: "materials-and-metallurgy", order: 1 },
  { id: "stainless-steel", slug: "stainless-steel", name: "Stainless Steel", level: 2, parentId: "materials-and-metallurgy", order: 2 },
  { id: "alloy-steel", slug: "alloy-steel", name: "Alloy Steel", level: 2, parentId: "materials-and-metallurgy", order: 3 },
  { id: "aluminium-products", slug: "aluminium-products", name: "Aluminium Products", level: 2, parentId: "materials-and-metallurgy", order: 4 },
  { id: "pipes-and-tubes", slug: "pipes-and-tubes", name: "Pipes & Tubes", level: 2, parentId: "materials-and-metallurgy", order: 5 },
  { id: "plates-and-sheets", slug: "plates-and-sheets", name: "Plates & Sheets", level: 2, parentId: "materials-and-metallurgy", order: 6 },
  { id: "structural-steel", slug: "structural-steel", name: "Structural Steel", level: 2, parentId: "materials-and-metallurgy", order: 7 },
  { id: "forgings", slug: "forgings", name: "Forgings", level: 2, parentId: "materials-and-metallurgy", order: 8 },
  { id: "castings", slug: "castings", name: "Castings", level: 2, parentId: "materials-and-metallurgy", order: 9 },
  { id: "composite-materials", slug: "composite-materials", name: "Composite Materials", level: 2, parentId: "materials-and-metallurgy", order: 10 },
  { id: "frp-products", slug: "frp-products", name: "FRP Products", level: 2, parentId: "materials-and-metallurgy", order: 11 },
  { id: "hdpe-products", slug: "hdpe-products", name: "HDPE Products", level: 2, parentId: "materials-and-metallurgy", order: 12 },
  { id: "cable-manufacturers", slug: "cable-manufacturers", name: "Cable Manufacturers", level: 2, parentId: "materials-and-metallurgy", order: 13 },
  // Civil/construction materials. The sheet above is metals- and polymer-led;
  // these cover what actually goes into tank foundations, ring beams and bund
  // walls. Refractory and insulation MATERIALS are added here deliberately as
  // the counterparts to AX-08 Refractory Services and EC-10 Insulation
  // Contractors, which previously had no materials-side equivalent.
  { id: "ready-mix-concrete", slug: "ready-mix-concrete", name: "Ready Mix Concrete", level: 2, parentId: "materials-and-metallurgy", order: 14 },
  { id: "cement-and-aggregates", slug: "cement-and-aggregates", name: "Cement & Aggregates", level: 2, parentId: "materials-and-metallurgy", order: 15 },
  { id: "refractory-materials", slug: "refractory-materials", name: "Refractory Materials", level: 2, parentId: "materials-and-metallurgy", order: 16 },
  { id: "insulation-materials", slug: "insulation-materials", name: "Insulation Materials", level: 2, parentId: "materials-and-metallurgy", order: 17 },
  { id: "industrial-supplies-mro", slug: "industrial-supplies-mro", name: "Industrial Supplies (MRO)", level: 1, parentId: "", order: 12 },
  { id: "fasteners", slug: "fasteners", name: "Fasteners", level: 2, parentId: "industrial-supplies-mro", order: 1 },
  { id: "gaskets", slug: "gaskets", name: "Gaskets", level: 2, parentId: "industrial-supplies-mro", order: 2 },
  { id: "bearings", slug: "bearings", name: "Bearings", level: 2, parentId: "industrial-supplies-mro", order: 3 },
  { id: "industrial-lubricants", slug: "industrial-lubricants", name: "Industrial Lubricants", level: 2, parentId: "industrial-supplies-mro", order: 4 },
  { id: "industrial-hoses", slug: "industrial-hoses", name: "Industrial Hoses", level: 2, parentId: "industrial-supplies-mro", order: 5 },
  { id: "industrial-rubber", slug: "industrial-rubber", name: "Industrial Rubber", level: 2, parentId: "industrial-supplies-mro", order: 6 },
  { id: "sealing-products", slug: "sealing-products", name: "Sealing Products", level: 2, parentId: "industrial-supplies-mro", order: 7 },
  { id: "industrial-plastics", slug: "industrial-plastics", name: "Industrial Plastics", level: 2, parentId: "industrial-supplies-mro", order: 8 },
  { id: "industrial-chemicals", slug: "industrial-chemicals", name: "Industrial Chemicals", level: 2, parentId: "industrial-supplies-mro", order: 9 },
  { id: "welding-consumables", slug: "welding-consumables", name: "Welding Consumables", level: 2, parentId: "industrial-supplies-mro", order: 10 },
  { id: "abrasives", slug: "abrasives", name: "Abrasives", level: 2, parentId: "industrial-supplies-mro", order: 11 },
  { id: "industrial-adhesives", slug: "industrial-adhesives", name: "Industrial Adhesives", level: 2, parentId: "industrial-supplies-mro", order: 12 },
  { id: "industrial-safety-equipment", slug: "industrial-safety-equipment", name: "Industrial Safety Equipment", level: 2, parentId: "industrial-supplies-mro", order: 13 },
  { id: "hand-tools", slug: "hand-tools", name: "Hand Tools", level: 2, parentId: "industrial-supplies-mro", order: 14 },
  { id: "power-tools", slug: "power-tools", name: "Power Tools", level: 2, parentId: "industrial-supplies-mro", order: 15 },
  { id: "logistics-and-transportation", slug: "logistics-and-transportation", name: "Logistics & Transportation", level: 1, parentId: "", order: 13 },
  { id: "port-operators", slug: "port-operators", name: "Port Operators", level: 2, parentId: "logistics-and-transportation", order: 1 },
  { id: "pipeline-operators", slug: "pipeline-operators", name: "Pipeline Operators", level: 2, parentId: "logistics-and-transportation", order: 2 },
  { id: "marine-logistics", slug: "marine-logistics", name: "Marine Logistics", level: 2, parentId: "logistics-and-transportation", order: 3 },
  { id: "shipping-companies", slug: "shipping-companies", name: "Shipping Companies", level: 2, parentId: "logistics-and-transportation", order: 4 },
  { id: "inland-waterways", slug: "inland-waterways", name: "Inland Waterways", level: 2, parentId: "logistics-and-transportation", order: 5 },
  { id: "rail-logistics", slug: "rail-logistics", name: "Rail Logistics", level: 2, parentId: "logistics-and-transportation", order: 6 },
  { id: "trucking-and-road-tankers", slug: "trucking-and-road-tankers", name: "Trucking & Road Tankers", level: 2, parentId: "logistics-and-transportation", order: 7 },
  { id: "freight-forwarding", slug: "freight-forwarding", name: "Freight Forwarding", level: 2, parentId: "logistics-and-transportation", order: 8 },
  { id: "customs-and-port-services", slug: "customs-and-port-services", name: "Customs & Port Services", level: 2, parentId: "logistics-and-transportation", order: 9 },
  { id: "warehouse-operators", slug: "warehouse-operators", name: "Warehouse Operators", level: 2, parentId: "logistics-and-transportation", order: 10 },
  { id: "cold-storage", slug: "cold-storage", name: "Cold Storage", level: 2, parentId: "logistics-and-transportation", order: 11 },
  { id: "marine-and-port-equipment", slug: "marine-and-port-equipment", name: "Marine & Port Equipment", level: 2, parentId: "logistics-and-transportation", order: 12 },
  { id: "utilities-and-energy", slug: "utilities-and-energy", name: "Utilities & Energy", level: 1, parentId: "", order: 14 },
  { id: "industrial-water-systems", slug: "industrial-water-systems", name: "Industrial Water Systems", level: 2, parentId: "utilities-and-energy", order: 1 },
  { id: "wastewater-treatment", slug: "wastewater-treatment", name: "Wastewater Treatment", level: 2, parentId: "utilities-and-energy", order: 2 },
  { id: "desalination", slug: "desalination", name: "Desalination", level: 2, parentId: "utilities-and-energy", order: 3 },
  { id: "steam-systems", slug: "steam-systems", name: "Steam Systems", level: 2, parentId: "utilities-and-energy", order: 4 },
  { id: "compressed-air", slug: "compressed-air", name: "Compressed Air", level: 2, parentId: "utilities-and-energy", order: 5 },
  { id: "power-generation", slug: "power-generation", name: "Power Generation", level: 2, parentId: "utilities-and-energy", order: 6 },
  // Emergency and standby power is a regulatory requirement at terminals, not
  // an optional extra — it runs fire water pumps, ESD and emergency lighting
  // when mains fails. These are genuinely different products from different
  // vendors, so they sit as L3 under Power Generation.
  { id: "diesel-generators", slug: "diesel-generators", name: "Diesel Generators & Gensets", level: 3, parentId: "power-generation", order: 1 },
  { id: "ups-systems", slug: "ups-systems", name: "UPS Systems", level: 3, parentId: "power-generation", order: 2 },
  { id: "power-distribution-equipment", slug: "power-distribution-equipment", name: "Power Distribution Equipment", level: 3, parentId: "power-generation", order: 3 },
  { id: "renewable-energy", slug: "renewable-energy", name: "Renewable Energy", level: 2, parentId: "utilities-and-energy", order: 7 },
  { id: "battery-energy-storage", slug: "battery-energy-storage", name: "Battery Energy Storage", level: 2, parentId: "utilities-and-energy", order: 8 },
  { id: "hydrogen-infrastructure", slug: "hydrogen-infrastructure", name: "Hydrogen Infrastructure", level: 2, parentId: "utilities-and-energy", order: 9 },
  { id: "utility-contractors", slug: "utility-contractors", name: "Utility Contractors", level: 2, parentId: "utilities-and-energy", order: 10 },
  { id: "sustainability-and-energy-transition", slug: "sustainability-and-energy-transition", name: "Sustainability & Energy Transition", level: 1, parentId: "", order: 15 },
  { id: "carbon-capture", slug: "carbon-capture", name: "Carbon Capture", level: 2, parentId: "sustainability-and-energy-transition", order: 1 },
  { id: "methane-reduction", slug: "methane-reduction", name: "Methane Reduction", level: 2, parentId: "sustainability-and-energy-transition", order: 2 },
  { id: "emissions-management", slug: "emissions-management", name: "Emissions Management", level: 2, parentId: "sustainability-and-energy-transition", order: 3 },
  { id: "emissions-control", slug: "emissions-control", name: "Emissions Control", level: 2, parentId: "sustainability-and-energy-transition", order: 4 },
  { id: "esg-consulting", slug: "esg-consulting", name: "ESG Consulting", level: 2, parentId: "sustainability-and-energy-transition", order: 5 },
  { id: "carbon-accounting", slug: "carbon-accounting", name: "Carbon Accounting", level: 2, parentId: "sustainability-and-energy-transition", order: 6 },
  { id: "renewable-fuels", slug: "renewable-fuels", name: "Renewable Fuels", level: 2, parentId: "sustainability-and-energy-transition", order: 7 },
  { id: "sustainable-aviation-fuel", slug: "sustainable-aviation-fuel", name: "Sustainable Aviation Fuel", level: 2, parentId: "sustainability-and-energy-transition", order: 8 },
  { id: "hydrogen-and-ammonia", slug: "hydrogen-and-ammonia", name: "Hydrogen & Ammonia", level: 2, parentId: "sustainability-and-energy-transition", order: 9 },
  { id: "circular-economy", slug: "circular-economy", name: "Circular Economy", level: 2, parentId: "sustainability-and-energy-transition", order: 10 },
  { id: "waste-management", slug: "waste-management", name: "Waste Management", level: 2, parentId: "sustainability-and-energy-transition", order: 11 },
  { id: "water-reuse", slug: "water-reuse", name: "Water Reuse", level: 2, parentId: "sustainability-and-energy-transition", order: 12 },
  { id: "net-zero-solutions", slug: "net-zero-solutions", name: "Net Zero Solutions", level: 2, parentId: "sustainability-and-energy-transition", order: 13 },
  { id: "professional-services", slug: "professional-services", name: "Professional Services", level: 1, parentId: "", order: 16 },
  { id: "project-consultants", slug: "project-consultants", name: "Project Consultants", level: 2, parentId: "professional-services", order: 1 },
  { id: "engineering-consultants", slug: "engineering-consultants", name: "Engineering Consultants", level: 2, parentId: "professional-services", order: 2 },
  { id: "consultancy-services", slug: "consultancy-services", name: "Consultancy Services", level: 2, parentId: "professional-services", order: 3 },
  { id: "owner-s-engineers", slug: "owner-s-engineers", name: "Owner's Engineers", level: 2, parentId: "professional-services", order: 4 },
  { id: "pmc-services", slug: "pmc-services", name: "PMC Services", level: 2, parentId: "professional-services", order: 5 },
  { id: "surveying", slug: "surveying", name: "Surveying", level: 2, parentId: "professional-services", order: 6 },
  { id: "gis-services", slug: "gis-services", name: "GIS Services", level: 2, parentId: "professional-services", order: 7 },
  { id: "environmental-consultants", slug: "environmental-consultants", name: "Environmental Consultants", level: 2, parentId: "professional-services", order: 8 },
  { id: "legal-services", slug: "legal-services", name: "Legal Services", level: 2, parentId: "professional-services", order: 9 },
  { id: "insurance", slug: "insurance", name: "Insurance", level: 2, parentId: "professional-services", order: 10 },
  { id: "financial-advisory", slug: "financial-advisory", name: "Financial Advisory", level: 2, parentId: "professional-services", order: 11 },
  { id: "digital-transformation", slug: "digital-transformation", name: "Digital Transformation", level: 2, parentId: "professional-services", order: 12 },
  { id: "procurement-services", slug: "procurement-services", name: "Procurement Services", level: 2, parentId: "professional-services", order: 13 },
  { id: "training-and-workforce", slug: "training-and-workforce", name: "Training & Workforce", level: 1, parentId: "", order: 17 },
  { id: "recruitment-and-jobs", slug: "recruitment-and-jobs", name: "Recruitment & Jobs", level: 2, parentId: "training-and-workforce", order: 1 },
  { id: "training-and-skilling", slug: "training-and-skilling", name: "Training & Skilling", level: 2, parentId: "training-and-workforce", order: 2 },
  { id: "technical-institutes", slug: "technical-institutes", name: "Technical Institutes", level: 2, parentId: "training-and-workforce", order: 3 },
  { id: "certification-bodies", slug: "certification-bodies", name: "Certification Bodies", level: 2, parentId: "training-and-workforce", order: 4 },
  { id: "industrial-staffing", slug: "industrial-staffing", name: "Industrial Staffing", level: 2, parentId: "training-and-workforce", order: 5 },
  { id: "contract-labour", slug: "contract-labour", name: "Contract Labour", level: 2, parentId: "training-and-workforce", order: 6 },
  { id: "executive-search", slug: "executive-search", name: "Executive Search", level: 2, parentId: "training-and-workforce", order: 7 },
  { id: "online-learning", slug: "online-learning", name: "Online Learning", level: 2, parentId: "training-and-workforce", order: 8 },
  { id: "competency-assessment", slug: "competency-assessment", name: "Competency Assessment", level: 2, parentId: "training-and-workforce", order: 9 },
  { id: "news-media-and-associations", slug: "news-media-and-associations", name: "News, Media & Associations", level: 1, parentId: "", order: 18 },
  { id: "news-and-media", slug: "news-and-media", name: "News & Media", level: 2, parentId: "news-media-and-associations", order: 1 },
  { id: "industry-associations", slug: "industry-associations", name: "Industry Associations", level: 2, parentId: "news-media-and-associations", order: 2 },
  { id: "standards-bodies", slug: "standards-bodies", name: "Standards Bodies", level: 2, parentId: "news-media-and-associations", order: 3 },

  // ── Renewables & Energy Storage (L1) ──────────────────────────────────
  // Added deliberately as its own sheet rather than folded into Sustainability:
  // ethanol blending, SATAT/CBG and the Green Hydrogen Mission are creating
  // storage requirements that differ materially from conventional hydrocarbons
  // (seal materials, coatings, corrosion behaviour, containment). Companies
  // specialising in exactly that need somewhere to land.
  { id: "renewables-and-energy-storage", slug: "renewables-and-energy-storage", name: "Renewables & Energy Storage", level: 1, parentId: "", order: 19 },
  { id: "solar-power-systems", slug: "solar-power-systems", name: "Solar Power Systems", level: 2, parentId: "renewables-and-energy-storage", order: 1 },
  { id: "bess-systems", slug: "bess-systems", name: "Battery Energy Storage (BESS)", level: 2, parentId: "renewables-and-energy-storage", order: 2 },
  { id: "hydrogen-storage-and-handling", slug: "hydrogen-storage-and-handling", name: "Hydrogen Storage & Handling", level: 2, parentId: "renewables-and-energy-storage", order: 3 },
  { id: "ammonia-storage-and-handling", slug: "ammonia-storage-and-handling", name: "Ammonia Storage & Handling", level: 2, parentId: "renewables-and-energy-storage", order: 4 },
  { id: "biofuel-and-ethanol-storage-systems", slug: "biofuel-and-ethanol-storage-systems", name: "Biofuel & Ethanol Storage Systems", level: 2, parentId: "renewables-and-energy-storage", order: 5 },
  { id: "cbg-and-biogas-infrastructure", slug: "cbg-and-biogas-infrastructure", name: "CBG & Biogas Infrastructure", level: 2, parentId: "renewables-and-energy-storage", order: 6 },
  { id: "carbon-capture-equipment", slug: "carbon-capture-equipment", name: "Carbon Capture Equipment", level: 2, parentId: "renewables-and-energy-storage", order: 7 },
  { id: "energy-efficiency-systems", slug: "energy-efficiency-systems", name: "Energy Efficiency Systems", level: 2, parentId: "renewables-and-energy-storage", order: 8 },

  // ── Inspection Equipment (L1) ─────────────────────────────────────────
  // The Asset Integrity sheet is entirely SERVICES — someone you hire. The
  // instruments themselves are a separate industry with separate vendors and
  // previously had no home anywhere in the tree.
  { id: "inspection-equipment", slug: "inspection-equipment", name: "Inspection Equipment", level: 1, parentId: "", order: 20 },
  { id: "ndt-equipment", slug: "ndt-equipment", name: "NDT Equipment", level: 2, parentId: "inspection-equipment", order: 1 },
  { id: "ultrasonic-flaw-detectors", slug: "ultrasonic-flaw-detectors", name: "Ultrasonic Flaw Detectors", level: 3, parentId: "ndt-equipment", order: 1 },
  { id: "thickness-gauges", slug: "thickness-gauges", name: "Thickness Gauges", level: 3, parentId: "ndt-equipment", order: 2 },
  { id: "phased-array-and-tofd", slug: "phased-array-and-tofd", name: "Phased Array & TOFD", level: 3, parentId: "ndt-equipment", order: 3 },
  { id: "tank-floor-scanners", slug: "tank-floor-scanners", name: "Tank Floor Scanners (MFL)", level: 2, parentId: "inspection-equipment", order: 2 },
  { id: "radiographic-equipment", slug: "radiographic-equipment", name: "Radiographic Equipment", level: 2, parentId: "inspection-equipment", order: 3 },
  { id: "weld-inspection-equipment", slug: "weld-inspection-equipment", name: "Weld Inspection Equipment", level: 2, parentId: "inspection-equipment", order: 4 },
  { id: "acoustic-emission-systems", slug: "acoustic-emission-systems", name: "Acoustic Emission Systems", level: 2, parentId: "inspection-equipment", order: 5 },
  { id: "borescopes-and-visual-inspection", slug: "borescopes-and-visual-inspection", name: "Borescopes & Visual Inspection", level: 2, parentId: "inspection-equipment", order: 6 },
  { id: "inspection-drones-and-crawlers", slug: "inspection-drones-and-crawlers", name: "Inspection Drones & Crawlers", level: 2, parentId: "inspection-equipment", order: 7 },
];
