// Auto-generated from tankonomics_companies_10_common.xlsx.
// The 10 launch companies (ASTSPARES ∩ TankBazaar). Doc id === slug (shared
// cross-app identity key). Seed via Admin → Companies → "Seed companies".

export interface CompanySeed {
  id: string; slug: string; name: string;
  description: string; aboutUs: string; address: string; website: string;
  logo: string; heroImage: string;
  linkedin: string; twitter: string; facebook: string; instagram: string;
  categoryIds: string[]; isFeatured: boolean;
}

export const COMPANY_SEED: CompanySeed[] = [
  {
    id: "bharat-petroleum-corporation-limited", slug: "bharat-petroleum-corporation-limited", name: "Bharat Petroleum Corporation Limited",
    description: "Maharatna PSU — crude refining and nationwide fuel marketing.", aboutUs: "",
    address: "Mumbai, Maharashtra, India", website: "https://www.bharatpetroleum.in",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1785497022/ChatGPT_Image_Jul_31_2026_04_47_40_PM_suhto3.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1785511648/BPCL_Cover_hjpwpc.png",
    linkedin: "https://www.linkedin.com/company/bpcl/posts/?feedView=all", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries"], isFeatured: false,
  },
  {
    id: "haldia-petrochemicals-limited", slug: "haldia-petrochemicals-limited", name: "Haldia Petrochemicals Limited",
    description: "Naphtha-based petrochemical producer (polymers, chemicals).", aboutUs: "",
    address: "Kolkata, West Bengal, India", website: "https://www.haldiapetrochemicals.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1785511648/HPL_LOGO_eswvav.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1785511858/HPL_COVER_zywued.png",
    linkedin: "https://www.linkedin.com/company/haldia-petrochemicals-ltd/posts/?feedView=all", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "petrochemicals"], isFeatured: false,
  },
  {
    id: "hindustan-petroleum-corporation-limited", slug: "hindustan-petroleum-corporation-limited", name: "Hindustan Petroleum Corporation Limited",
    description: "Maharatna PSU refiner and fuel marketer.", aboutUs: "",
    address: "Mumbai, Maharashtra, India", website: "https://www.hindustanpetroleum.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1785511648/HPCL_Logo_gaoo4o.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1785510278/HPCL_COVER_PHOTO_st0wlu.png",
    linkedin: "https://www.linkedin.com/company/hpcl/posts/?feedView=all", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries"], isFeatured: false,
  },
  {
    id: "indian-oil-corporation-limited", slug: "indian-oil-corporation-limited", name: "Indian Oil Corporation Limited",
    description: "India's largest refiner and fuel marketer (Maharatna PSU).", aboutUs: "",
    address: "New Delhi, India", website: "https://www.iocl.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1785511648/IOC_LOGO_pwclxf.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1785497094/IOCIANS_qpgudb.png",
    linkedin: "https://www.linkedin.com/company/indian-oil-corp-limited/posts/?feedView=all", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries", "petrochemicals"], isFeatured: false,
  },
  {
    id: "mangalore-refinery-and-petrochemicals-limited", slug: "mangalore-refinery-and-petrochemicals-limited", name: "Mangalore Refinery and Petrochemicals Limited",
    description: "Refinery & petrochemicals; ONGC subsidiary.", aboutUs: "",
    address: "Mangalore, Karnataka, India", website: "https://www.mrpl.co.in",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1785511649/MRPL_LOGO_qrimij.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1785497100/MRPL_Refinery_pplojb.jpg",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries", "petrochemicals"], isFeatured: false,
  },
  {
    id: "nayara-energy-limited", slug: "nayara-energy-limited", name: "Nayara Energy Limited",
    description: "Refining and fuel retail; operates the Vadinar refinery.", aboutUs: "",
    address: "Mumbai, Maharashtra, India", website: "https://www.nayaraenergy.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1785511853/Nayara_htuzhx.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1785497092/Nayara_cover_awpxzh.png",
    linkedin: "https://www.linkedin.com/company/nayaraenergy/posts/?feedView=all", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries"], isFeatured: false,
  },
  {
    id: "ongc-petro-additions-limited", slug: "ongc-petro-additions-limited", name: "ONGC Petro Additions Limited",
    description: "Petrochemical complex at Dahej (ONGC-promoted; 'OPaL').", aboutUs: "",
    address: "Dahej, Gujarat, India", website: "https://www.opalindia.in",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1785511649/OPAL_i53fie.webp",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1785510039/OPAL_COVER_uwaod3.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "petrochemicals"], isFeatured: false,
  },
  {
    id: "oil-and-natural-gas-corporation-limited", slug: "oil-and-natural-gas-corporation-limited", name: "Oil and Natural Gas Corporation Limited",
    description: "India's largest crude oil & natural gas E&P company (Maharatna PSU).", aboutUs: "",
    address: "New Delhi, India", website: "https://www.ongcindia.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1785511647/ONGC_LOGO_h2o4gc.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1785510448/ONGC_COVER_sjytrx.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["natural-resources-and-upstream", "oil-and-gas-exploration"], isFeatured: false,
  },
  {
    id: "reliance-industries-limited", slug: "reliance-industries-limited", name: "Reliance Industries Limited",
    description: "Refining, petrochemicals and more; operates Jamnagar (world's largest refinery).", aboutUs: "",
    address: "Mumbai, Maharashtra, India", website: "https://www.ril.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1785511649/RIL_axh1dy.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1785510039/RIL_Cover_Image_gkko1p.png",
    linkedin: "https://www.linkedin.com/company/reliance/posts/?feedView=all", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries", "petrochemicals"], isFeatured: false,
  },
  {
    id: "tamil-nadu-petroproducts-limited", slug: "tamil-nadu-petroproducts-limited", name: "Tamil Nadu Petroproducts Limited",
    description: "Petrochemicals / specialty chemicals (LAB, epichlorohydrin).", aboutUs: "",
    address: "Chennai, Tamil Nadu, India", website: "https://www.tnpetro.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1785511649/TNPETRO_LOGO_nmce7c.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1785512376/TNPetro_pjt0ka.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "petrochemicals", "chemicals"], isFeatured: false,
  },
  {
    id: "koninklijke-vopak-nv", slug: "koninklijke-vopak-nv", name: "Koninklijke Vopak N.V.",
    description: "Independent tank storage operator; world's largest, with terminals across Europe, Asia and the Americas.", aboutUs: "",
    address: "Rotterdam, Netherlands", website: "https://www.vopak.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786019731/VOPAK_mv0wm7.jpg",
    heroImage: "",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "kinder-morgan-inc", slug: "kinder-morgan-inc", name: "Kinder Morgan Inc",
    description: "One of North America's largest energy infrastructure companies; pipelines and terminals across the USA.", aboutUs: "",
    address: "Houston, Texas, USA", website: "https://www.kindermorgan.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786019732/kinder-morgan-logo-png-transparent_fdji2b.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786019738/KMI_Cover_nonww0.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "china-petroleum-and-chemical-corporation-sinopec-corp", slug: "china-petroleum-and-chemical-corporation-sinopec-corp", name: "China Petroleum & Chemical Corporation (Sinopec Corp.)",
    description: "Chinese state-controlled refining and petrochemical major; one of Asia's largest integrated energy companies.", aboutUs: "",
    address: "Beijing, China", website: "https://www.sinopec.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786019731/Sinopec_jqhh9e.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786019738/Sinopec_Cover_egk7to.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries", "petrochemicals"], isFeatured: false,
  },
  {
    id: "oiltanking-gmbh", slug: "oiltanking-gmbh", name: "Oiltanking GmbH",
    description: "Independent tank storage operator headquartered in Hamburg, with terminals across Europe and beyond.", aboutUs: "",
    address: "Hamburg, Germany", website: "https://www.oiltanking.com",
    logo: "",
    heroImage: "",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "petrochina-company-limited", slug: "petrochina-company-limited", name: "PetroChina Company Limited",
    description: "China's largest oil and gas producer and refiner, listed subsidiary of CNPC.", aboutUs: "",
    address: "Beijing, China", website: "https://www.petrochina.com.cn",
    logo: "",
    heroImage: "",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries", "petrochemicals"], isFeatured: false,
  },
  {
    id: "vtti-bv", slug: "vtti-bv", name: "VTTI B.V.",
    description: "Independent energy storage operator with terminals across five continents; co-owned by Vitol, IFM and ADNOC.", aboutUs: "",
    address: "Rotterdam, Netherlands", website: "https://www.vtti.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786019731/VTTI_dqbflt.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786019614/VTTI_Cover_zawqlz.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "advario-bv", slug: "advario-bv", name: "Advario B.V",
    description: "Global tank storage operator for chemicals, gases and new energy; carved out of Oiltanking in 2022.", aboutUs: "",
    address: "Rotterdam, Netherlands", website: "https://advario.com",
    logo: "",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786019738/ADVARIO_COVER_w1elm7.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "tepsa-infra-sas", slug: "tepsa-infra-sas", name: "Tepsa Infra SAS",
    description: "Independent liquid bulk storage operator across Western Europe; rebranded from Rubis Terminal in 2024.", aboutUs: "",
    address: "Paris, France", website: "https://tepsa.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786019730/TEPSA_LOGO_vvmetl.jpg",
    heroImage: "",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "aegis-vopak-terminals-limited", slug: "aegis-vopak-terminals-limited", name: "Aegis Vopak Terminals Limited",
    description: "India's largest independent LPG and liquid storage network; NSE-listed JV between Aegis Logistics and Royal Vopak.", aboutUs: "",
    address: "Mumbai, Maharashtra, India", website: "https://www.aegisvopak.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786019732/kinder-morgan-logo-png-transparent_fdji2b.png",
    heroImage: "",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "exolum-terminals-ltd", slug: "exolum-terminals-ltd", name: "Exolum Terminals Ltd",
    description: "UK arm of Exolum, the Spanish-origin oil products storage and pipeline group (formerly CLH).", aboutUs: "",
    address: "London, United Kingdom", website: "https://www.exolum.com",
    logo: "",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786019616/Exolum_Cover_real_syrrr7.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "exxon-mobil-corporation", slug: "exxon-mobil-corporation", name: "Exxon Mobil Corporation",
    description: "Global integrated oil, gas and petrochemicals major.", aboutUs: "",
    address: "Irving, Texas, USA", website: "https://corporate.exxonmobil.com",
    logo: "",
    heroImage: "",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries", "petrochemicals"], isFeatured: false,
  },
  {
    id: "national-petroleum-and-natural-gas-pipeline-group-co-ltd", slug: "national-petroleum-and-natural-gas-pipeline-group-co-ltd", name: "National Petroleum and Natural Gas Pipeline Group Co., Ltd.",
    description: "China's national oil & gas pipeline network operator (“PipeChina”), formed 2019 from CNPC/Sinopec/CNOOC midstream assets.", aboutUs: "",
    address: "Beijing, China", website: "",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786019606/PIPECHINA_luremd.webp",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786019610/PIPECHINA_COVER_REAL_rwqjm9.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "pt-pertamina", slug: "pt-pertamina", name: "PT Pertamina",
    description: "Indonesia's state-owned oil and gas company; refining, distribution and E&P.", aboutUs: "",
    address: "Jakarta, Indonesia", website: "https://www.pertamina.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786019607/Pertamina_f3xd3s.jpg",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786019610/PT_Petramina_Cover_real_fjlvzn.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries"], isFeatured: false,
  },
  {
    id: "petroleo-brasileiro-sa-petrobras", slug: "petroleo-brasileiro-sa-petrobras", name: "Petróleo Brasileiro S.A. – Petrobras",
    description: "Brazil's state-controlled oil, gas and biofuels major.", aboutUs: "",
    address: "Rio de Janeiro, Brazil", website: "https://petrobras.com.br",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786019605/Petrobras_dykduo.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786019611/Petrobras_cover_qwpmk5.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries", "fertilisers"], isFeatured: false,
  },
  {
    id: "imc-limited", slug: "imc-limited", name: "IMC Limited",
    description: "India's largest independent bulk liquid storage company; port-based terminals since 1950.", aboutUs: "",
    address: "Chennai, Tamil Nadu, India", website: "https://www.imc.net.in",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786019605/imc_limited_logo_kx69dy.jpg",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786019611/IMC_Cover_real_wcesl6.png",
    linkedin: "", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "chennai-petroleum-corporation-limited", slug: "chennai-petroleum-corporation-limited", name: "Chennai Petroleum Corporation Limited",
    description: "South India's leading refiner; subsidiary of Indian Oil, operating the Manali and Cauvery Basin refineries.", aboutUs: "",
    address: "536, Anna Salai, Teynampet, Chennai, Tamil Nadu, India", website: "https://cpcl.co.in",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786024796/cpcl_logo_pumipf.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786024797/cpcl_cover_w6bmwu.jpg",
    linkedin: "https://www.linkedin.com/company/chennai-petroleum-corp.-ltd-indian-oil-/home/", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries"], isFeatured: false,
  },
  {
    id: "puma-energy-holdings-pte-ltd", slug: "puma-energy-holdings-pte-ltd", name: "Puma Energy Holdings Pte. Ltd.",
    description: "Global midstream and downstream energy company; majority-owned by Trafigura, operating across ~40 countries.", aboutUs: "",
    address: "10 Collyer Quay, Ocean Financial Centre, Singapore", website: "https://www.pumaenergy.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786024796/puma_energy_logo_its4kf.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786024796/puma_energy_cover_aolo2d.webp",
    linkedin: "https://www.linkedin.com/company/puma-energy/home/", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "eneos-corporation", slug: "eneos-corporation", name: "ENEOS Corporation",
    description: "Japan's largest oil refiner and petroleum products marketer.", aboutUs: "",
    address: "Tokyo, Japan", website: "https://www.eneos.co.jp/english/",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786024796/eneos-logo-png_seeklogo-47800_wzopst.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786024796/eneos_cover_llrmkz.jpg",
    linkedin: "https://www.linkedin.com/company/eneosgroup/home/", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries"], isFeatured: false,
  },
  {
    id: "ecopetrol-sa", slug: "ecopetrol-sa", name: "Ecopetrol S.A.",
    description: "Colombia's state-controlled integrated oil and gas major.", aboutUs: "",
    address: "Bogotá, Colombia", website: "https://www.ecopetrol.com.co",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786024795/Ecopetrol_logo_v4apaf.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786024796/ecopetrol_cover_qnswli.webp",
    linkedin: "https://www.linkedin.com/company/ecopetroloficial/home/", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries"], isFeatured: false,
  },
  {
    id: "equinor-asa", slug: "equinor-asa", name: "Equinor ASA",
    description: "Norway's state-controlled energy major; oil, gas and renewables.", aboutUs: "",
    address: "Stavanger, Norway", website: "https://www.equinor.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786024795/Equinor-Logo.wine_rj9wzo.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786024796/Equinor_cover_urlidl.jpg",
    linkedin: "https://www.linkedin.com/company/equinor/home/", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries"], isFeatured: false,
  },
  {
    id: "exolum-corporation-sa", slug: "exolum-corporation-sa", name: "Exolum Corporation, S.A.",
    description: "Spanish parent of the Exolum group (formerly CLH); oil products storage and pipeline logistics.", aboutUs: "",
    address: "Madrid, Spain", website: "https://www.exolum.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786024795/exolum_logo_uynhyk.jpg",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786024796/exolum_cover_uwb48l.jpg",
    linkedin: "https://www.linkedin.com/company/exolum/home/", twitter: "", facebook: "", instagram: "",
    categoryIds: ["storage-terminals"], isFeatured: false,
  },
  {
    id: "grupa-azoty-sa", slug: "grupa-azoty-sa", name: "Grupa Azoty S.A.",
    description: "Poland's largest chemical company and the EU's second-largest fertiliser producer.", aboutUs: "",
    address: "Tarnów, Poland", website: "https://grupaazoty.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786024794/grupa_azoty_logo_irsob9.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786024795/grupa-azoty_z2xlje.png",
    linkedin: "https://www.linkedin.com/company/grupa-azoty-s.a./home/", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "fertilisers"], isFeatured: false,
  },
  {
    id: "petroleos-de-venezuela-sa", slug: "petroleos-de-venezuela-sa", name: "Petróleos de Venezuela, S.A.",
    description: "Venezuela's state-owned oil company (PDVSA).", aboutUs: "",
    address: "Caracas, Venezuela", website: "https://www.pdvsa.com",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786024794/pdvsa_logo_fwzxae.jpg",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786024794/pdvsa_cover_k4xh5q.jpg",
    linkedin: "https://www.linkedin.com/company/pdvsa-ve/home/", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries"], isFeatured: false,
  },
  {
    id: "turkiye-petrol-rafinerileri-as-tupras", slug: "turkiye-petrol-rafinerileri-as-tupras", name: "Türkiye Petrol Rafinerileri A.Ş. (Tüpraş)",
    description: "Turkey's sole refiner; operates four refineries covering the country's entire refining capacity.", aboutUs: "",
    address: "Kocaeli, Turkey", website: "https://www.tupras.com.tr",
    logo: "https://res.cloudinary.com/petrodek/image/upload/v1786024794/tupras-logo-png_seeklogo-143105_mqe60b.png",
    heroImage: "https://res.cloudinary.com/petrodek/image/upload/v1786024794/tupras_cover_lnf30m.webp",
    linkedin: "https://www.linkedin.com/company/tupras/posts/", twitter: "", facebook: "", instagram: "",
    categoryIds: ["process-industries", "refineries"], isFeatured: false,
  },
];
